# Rent Contracts Dataset Cleaning and Preparation

## Objective
In this notebook, we aim to clean, prepare, and explore the rent contracts dataset. Our goal is to align this dataset with the transactions data, facilitating rental yield analysis and further enhancing our real estate market insights.



## Data Collection and Cleaning for Rent Contracts

In this notebook, we’ll focus on the **Rent Contracts** dataset, loading and inspecting it to ensure it’s clean and well-structured for analysis. Our initial steps involve exploring the dataset’s structure, identifying key variables, and addressing any missing or inconsistent data. This foundational work on the rent contracts data will align it with the **Transactions** dataset, allowing us to seamlessly integrate both datasets in future steps. With a well-prepared dataset, we’ll be set up to derive insights and conduct rental yield analysis to support our project objectives.

In [2]:
# Importing libraries
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [3]:
# Loading dataset
rent_contracts = pd.read_csv("../data/raw/rent_contracts.csv")

In [4]:
# Setting pandas and numpy setting to display all rows and columns
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
np.set_printoptions(threshold=np.inf)

In [5]:
# Displaying random observations from rent contracts dataset
print(rent_contracts.sample(5))

           contract_id  contract_reg_type_id contract_reg_type_ar  \
1356075   CRT481616026                     2                تجديد   
3911921  CNT1929052718                     1                 جديد   
5520893  CNT2112573971                     2                تجديد   
1623093   CRT797476206                     1                 جديد   
4862124  CNT2089239297                     2                تجديد   

        contract_reg_type_en contract_start_date contract_end_date  \
1356075                Renew          01-05-2016        30-04-2017   
3911921                  New          12-07-2022        11-07-2023   
5520893                Renew          18-12-2023        17-12-2024   
1623093                  New          20-04-2018        19-04-2028   
4862124                Renew          12-06-2023        11-09-2023   

         contract_amount  annual_amount  no_of_prop  line_number  \
1356075            42000          42000           1            1   
3911921            28000    

In [6]:
# Displaying information about rent contracts dataset
print(rent_contracts.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8171211 entries, 0 to 8171210
Data columns (total 40 columns):
 #   Column                      Dtype  
---  ------                      -----  
 0   contract_id                 object 
 1   contract_reg_type_id        int64  
 2   contract_reg_type_ar        object 
 3   contract_reg_type_en        object 
 4   contract_start_date         object 
 5   contract_end_date           object 
 6   contract_amount             int64  
 7   annual_amount               int64  
 8   no_of_prop                  int64  
 9   line_number                 int64  
 10  is_free_hold                float64
 11  ejari_bus_property_type_id  float64
 12  ejari_bus_property_type_ar  object 
 13  ejari_bus_property_type_en  object 
 14  ejari_property_type_id      float64
 15  ejari_property_type_en      object 
 16  ejari_property_type_ar      object 
 17  ejari_property_sub_type_id  float64
 18  ejari_property_sub_type_en  object 
 19  ejari_property_sub_ty

In [7]:
# Displaying missing values in rent contracts dataset
rent_contracts.isnull().sum() / rent_contracts.shape[0] * 100

contract_id                    0.000000
contract_reg_type_id           0.000000
contract_reg_type_ar           0.000000
contract_reg_type_en           0.000000
contract_start_date            0.000000
contract_end_date              0.000000
contract_amount                0.000000
annual_amount                  0.000000
no_of_prop                     0.000000
line_number                    0.000000
is_free_hold                   0.036115
ejari_bus_property_type_id     0.036115
ejari_bus_property_type_ar     0.036115
ejari_bus_property_type_en     0.036115
ejari_property_type_id         0.708218
ejari_property_type_en         0.722378
ejari_property_type_ar         0.722378
ejari_property_sub_type_id     0.736672
ejari_property_sub_type_en     0.803235
ejari_property_sub_type_ar     0.803235
property_usage_en              0.175103
property_usage_ar              0.175103
project_number                85.635250
project_name_ar               85.635250
project_name_en               85.635250


**Key Observations**

1. **Contract and Tenant Information**:

    - **Essential Contract Data**: Each record has `contract_id`, `contract_reg_type_en` (**New** or **Renew**), and contract duration (`contract_start_date` and `contract_end_date`), which provide insights into the contract type and period. This information is crucial for analyzing trends over time, particularly in contract renewals versus new agreements.

    - **Tenant Information**: The `tenant_type_en` column specifies whether the tenant is a **Person** or **Authority**. However, it has a **9.6%** missing rate, indicating some records lack tenant type, which might impact tenant-based segmentation.

2. **Property and Usage Details**:

    - **Property Classification**:

        - **Broad Categories**: `ejari_bus_property_type_en` and `ejari_property_type_en` offer classifications like **Unit**, **Land**, **Office**, and **Shop**. However, the primary property usage (`property_usage_en`) includes **Residential**, **Commercial**, and **Industrial / Commercial** categories.

        - **Detailed Subtypes**: `ejari_property_sub_type_en` specifies unit configurations (e.g., **1-bedroom**, **Shop**) but has **80%** missing data, which may limit the level of detail in analysis.

        - The `is_free_hold` column, indicating whether the property is freehold, is missing in **3.6%** of records.

        - **Single Property Contracts**: `no_of_prop` indicates the number of properties per contract. A value of 1 suggests single-property contracts, which may simplify yield analysis by focusing on individual units.


3. **Location Information**:

    - **Area and Project Data**:

        - `area_name_en` and `area_id` provide general location information with minimal missing values.

        - The `project_number`, `project_name_en`, and `master_project_en` columns give insights into specific projects, but they have high missing rates (**85.6%** and **67.8%** respectively), indicating limited project-level information in many records.

    - **Proximity to Key Amenities**:

        - Fields such as `nearest_landmark_en`, `nearest_metro_en`, and `nearest_mall_en` describe the proximity of properties to landmarks, metro stations, and malls. Missing values range from 6.7% to 11.3%, which may impact completeness in location-based analysis.


4. **Financial Details**:

    - **Rent Amounts and Area**:

        - `contract_amount` and `annual_amount` fields capture the rental amounts, and `actual_area` provides the area (m²) of the unit. However, `actual_area` is missing in **11.1%** of records, which may affect price-per-area calculations for rental yield analysis.

### Data Preparation and Initial Filtering of Rent Contracts Dataset

To ensure that our **Rent Contracts** dataset is relevant, manageable, and aligned with our project’s objectives, we begin by preparing and filtering the data in a few key ways:

1. **Convert Date Columns**: The `contract_start_date` and `contract_end_date` columns are first converted into datetime format. This standardization allows us to perform accurate date-based operations, enabling efficient filtering and future analysis based on timeframes.

2. **Focus on Recent Data (Last 3 Years)**: Given that recent trends are most relevant to our analysis, we filter the dataset to include only contracts from the past three years. This step substantially reduces the dataset size, helping us focus on the most pertinent and up-to-date information.

3. **Remove Arabic Columns**: To simplify the dataset, we remove all columns with Arabic text (`_ar` suffix). This leaves only the English attributes, streamlining the data and improving readability for subsequent processing steps.

4. **Filter for Residential Properties with Single Units**: 

   - We narrow down the dataset further to focus solely on **Residential** property contracts, discarding any non-residential entries.

   - Additionally, we filter for contracts involving a single property unit (`no_of_prop = 1`). This ensures that our data reflects individual rental units, aligning with our objectives for rental yield calculations and simplifying the modeling process.

In [8]:
# Displaying random observations from the date columns
print(rent_contracts['contract_start_date'].sample(5))
print(rent_contracts['contract_end_date'].sample(5))

3386607    25-10-2021
3875655    25-04-2022
1667356    01-09-2018
4653603    29-04-2023
3168732    14-07-2021
Name: contract_start_date, dtype: object
212298     31-10-2021
6103150    31-08-2015
2649152    15-07-2021
7343510    09-09-2014
2619479    07-09-2021
Name: contract_end_date, dtype: object


In [9]:
# Converting date columns to datetime format
rent_contracts['contract_start_date_converted'] = pd.to_datetime(rent_contracts['contract_start_date'], dayfirst=True, errors='coerce')
rent_contracts['contract_end_date_converted'] = pd.to_datetime(rent_contracts['contract_end_date'], dayfirst=True, errors='coerce')

# Displaying random observations from the date columns
print(rent_contracts['contract_start_date_converted'].sample(5))
print(rent_contracts['contract_end_date_converted'].sample(5))

3716560   2022-03-01
6304374   2015-03-25
6205904   2015-01-14
7333856   2012-07-08
1597347   2018-03-01
Name: contract_start_date_converted, dtype: datetime64[ns]
2609438   2021-09-07
2239001   2021-03-14
2604638   2013-12-14
8128711   2019-11-19
7519302   2018-12-14
Name: contract_end_date_converted, dtype: datetime64[ns]


In [10]:
# Comparing the original date columns with the converted date columns missing values
rent_contracts[[col for col in rent_contracts.columns if 'date' in col]].isnull().sum() / rent_contracts.shape[0] * 100

contract_start_date              0.000000
contract_end_date                0.000000
contract_start_date_converted    0.000000
contract_end_date_converted      0.000024
dtype: float64

In [11]:
# Inpecting the missing values in the converted date columns
rent_contracts[rent_contracts['contract_end_date_converted'].isna()].shape 

(2, 42)

In [12]:
# Displaying the missing values in the converted date columns
display(rent_contracts[rent_contracts['contract_end_date_converted'].isna()])

contract_id  contract_reg_type_id contract_reg_type_ar  \
7142575    CNT58327                     1                 جديد   
7144099    CNT58873                     1                 جديد   

        contract_reg_type_en contract_start_date contract_end_date  \
7142575                  New          29-05-2012        28-05-5013   
7144099                  New          01-04-2012        31-03-3013   

         contract_amount  annual_amount  no_of_prop  line_number  \
7142575        180060000          60000           1            1   
7144099         18018000          18000           1            1   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_ar  \
7142575           0.0                         2.0                       وحدة   
7144099           0.0                         2.0                       وحدة   

        ejari_bus_property_type_en  ejari_property_type_id  \
7142575                       Unit                   842.0   
7144099                       Unit                   842.0   

        ejari_property_type_en ejari_property_type_ar  \
7142575                   Flat                    شقه   
7144099                   Flat                    شقه   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
7142575                         2.0           2 bed rooms+hall   
7144099                        11.0                     Studio   

        ejari_property_sub_type_ar property_usage_en property_usage_ar  \
7142575              غرفتين و صالة       Residential              سكني   
7144099                    أستوديو       Residential              سكني   

         project_number project_name_ar project_name_en master_project_ar  \
7142575             NaN             NaN             NaN               NaN   
7144099             NaN             NaN             NaN               NaN   

        master_project_en  area_id   area_name_ar    area_name_en  \
7142575               NaN    355.0  النهده الاولى  Al Nahda First   
7144099               NaN    362.0           نايف            Naif   

         actual_area nearest_landmark_ar          nearest_landmark_en  \
7142575        137.0     مطار دبي الدولي  Dubai International Airport   
7144099         24.0     مطار دبي الدولي  Dubai International Airport   

                nearest_metro_ar              nearest_metro_en  \
7142575        محطة مترو الاستاد         STADIUM Metro Station   
7144099  محطة مترو ميدان بني ياس  Baniyas Square Metro Station   

        nearest_mall_ar     nearest_mall_en  tenant_type_id tenant_type_ar  \
7142575  سيتي سنتر مردف  City Centre Mirdif             1.0            شخص   
7144099         مول دبي          Dubai Mall             1.0            شخص   

        tenant_type_en contract_start_date_converted  \
7142575         Person                    2012-05-29   
7144099         Person                    2012-04-01   

        contract_end_date_converted  
7142575                         NaT  
7144099                         NaT

Given that these date errors fall far outside your three-year filter, it’s reasonable to proceed with the direct conversion in the original columns and use `errors='coerce'` to handle any non-standard dates. This approach will help you bypass the need for new columns while ensuring any invalid dates become `NaT`, which won't affect your filtering process.

In [13]:
# Deleting the created date columns
rent_contracts.drop(columns=['contract_start_date_converted', 'contract_end_date_converted'], inplace=True)

# Converting the original date columns to datetime format
rent_contracts['contract_start_date'] = pd.to_datetime(rent_contracts['contract_start_date'], dayfirst=True, errors='coerce')
rent_contracts['contract_end_date'] = pd.to_datetime(rent_contracts['contract_end_date'], dayfirst=True, errors='coerce')

# Inspecting the data type for the date columns
rent_contracts[['contract_start_date', 'contract_end_date']].dtypes

contract_start_date    datetime64[ns]
contract_end_date      datetime64[ns]
dtype: object

In [14]:
# Filtering the dataset to only include obsvertaions from the last 3 years
from datetime import datetime 
rent_contracts_3y = rent_contracts[rent_contracts['contract_start_date'].dt.year >= datetime.now().year - 3]

# Comparing shapes before and after filtering
print("Rent Contracts Shape Before Filtering:", rent_contracts.shape)
print("Rent Contracts Shape After Filtering:", rent_contracts_3y.shape)

Rent Contracts Shape Before Filtering: (8171211, 40)
Rent Contracts Shape After Filtering: (3547373, 40)


In [15]:
# Removing Arabic columns from the dataset
arabic_cols = [col for col in rent_contracts_3y.columns if col.endswith("_ar")]
rent_contracts_3y = rent_contracts_3y.drop(columns=arabic_cols)

In [16]:
# Inspecting the shape of the dataset after removing Arabic columns
print(rent_contracts_3y.shape)

(3547373, 28)


In [17]:
# Displaying random observations from the dataset
display(rent_contracts_3y.sample(5))

contract_id  contract_reg_type_id contract_reg_type_en  \
3606409  CNT1828540034                     2                Renew   
5100341  CNT2101252815                     1                  New   
3476572  CNT1781056065                     2                Renew   
4073688  CNT1984328005                     1                  New   
3492123  CNT1786848088                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
3606409          2022-01-15        2023-01-14           138000         138000   
5100341          2023-11-17        2024-11-16            50000          50000   
3476572          2021-11-09        2022-11-08           130000         130000   
4073688          2022-08-23        2023-08-22            15000          15000   
3492123          2021-11-15        2022-11-14           110000         110000   

         no_of_prop  line_number  is_free_hold  ejari_bus_property_type_id  \
3606409           1            1           1.0                         4.0   
5100341           1            1           1.0                         2.0   
3476572           1            1           0.0                         4.0   
4073688           1            1           0.0                         2.0   
3492123           1            1           0.0                         4.0   

        ejari_bus_property_type_en  ejari_property_type_id  \
3606409                      Villa                   841.0   
5100341                       Unit                   842.0   
3476572                      Villa                    19.0   
4073688                       Unit                     2.0   
3492123                      Villa                   841.0   

        ejari_property_type_en  ejari_property_sub_type_id  \
3606409                  Villa                         3.0   
5100341                   Flat                         1.0   
3476572         Complex Villas                         4.0   
4073688                 Office                       422.0   
3492123                  Villa                         3.0   

        ejari_property_sub_type_en property_usage_en  project_number  \
3606409           3 bed rooms+hall       Residential             NaN   
5100341             1bed room+Hall       Residential             NaN   
3476572           4 bed rooms+hall       Residential             NaN   
4073688                     Office        Commercial             NaN   
3492123           3 bed rooms+hall       Residential             NaN   

        project_name_en master_project_en  area_id     area_name_en  \
3606409             NaN     Silicon Oasis    484.0       Nadd Hessa   
5100341             NaN               NaN    464.0   Wadi Al Safa 2   
3476572             NaN               NaN    317.0   Jumeirah First   
4073688             NaN               NaN    235.0      Eyal Nasser   
3492123             NaN               NaN    375.0  Jumeirah Second   

         actual_area          nearest_landmark_en            nearest_metro_en  \
3606409        341.0         IMG World Adventures                         NaN   
5100341         70.0         IMG World Adventures                         NaN   
3476572        214.0                 Burj Khalifa            Financial Centre   
4073688         10.0  Dubai International Airport   Palm Deira Metro Stations   
3492123        211.0                 Burj Khalifa  Business Bay Metro Station   

            nearest_mall_en  tenant_type_id tenant_type_en  
3606409  City Centre Mirdif             1.0         Person  
5100341                 NaN             1.0         Person  
3476572          Dubai Mall             1.0         Person  
4073688          Dubai Mall             2.0      Authority  
3492123          Dubai Mall             1.0         Person

In [18]:
# Inspecting missing values percentages of the dataset
rent_contracts_3y.isnull().sum() / rent_contracts_3y.shape[0] * 100

contract_id                    0.000000
contract_reg_type_id           0.000000
contract_reg_type_en           0.000000
contract_start_date            0.000000
contract_end_date              0.000000
contract_amount                0.000000
annual_amount                  0.000000
no_of_prop                     0.000000
line_number                    0.000000
is_free_hold                   0.000226
ejari_bus_property_type_id     0.000226
ejari_bus_property_type_en     0.000226
ejari_property_type_id         0.493097
ejari_property_type_en         0.508320
ejari_property_sub_type_id     0.510124
ejari_property_sub_type_en     0.576511
property_usage_en              0.090405
project_number                82.176275
project_name_en               82.176275
master_project_en             64.823237
area_id                        0.000085
area_name_en                   0.000085
actual_area                   11.296359
nearest_landmark_en            7.228983
nearest_metro_en              12.564594


In [19]:
# Inspecting values of Property Usage column
rent_contracts_3y['property_usage_en'].value_counts()

property_usage_en
Residential                              2492719
Commercial                               1014027
Industrial                                 20305
Industrial / Commercial                     7223
Multi Usage                                 3652
Industrial / Commercial / Residential       1861
Storage                                     1675
Tourist origin                              1463
Educational facility                         543
Health Facility                              472
Residential / Commercial                     169
Agriculture                                   57
Name: count, dtype: int64

In [20]:
# Filtrering the dataset to only include residential properties
rent_contracts_residential_3y = rent_contracts_3y[rent_contracts_3y['property_usage_en'] == 'Residential']

# Comparing shapes before and after filtering
print("Rent Contracts Before Filtering:", rent_contracts_3y.shape)
print("Rent Contracts After Filtering:", rent_contracts_residential_3y.shape)

Rent Contracts Before Filtering: (3547373, 28)
Rent Contracts After Filtering: (2492719, 28)


In [21]:
# Removing "property_usage_en" since the property usage column only holds a single value
rent_contracts_residential_3y = rent_contracts_residential_3y.drop(columns='property_usage_en')

# Confirming removal of column
rent_contracts_residential_3y.shape 

(2492719, 27)

In [22]:
# Displaying random observations from the dataset
display(rent_contracts_residential_3y.sample(5))

contract_id  contract_reg_type_id contract_reg_type_en  \
3054889  CNT1452684697                     2                Renew   
4033793  CNT1971243629                     2                Renew   
830263   CRT2100803076                     2                Renew   
3242116  CNT1563187925                     1                  New   
5499457  CNT2112264240                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
3054889          2021-03-28        2022-03-27            45000          45000   
4033793          2022-08-19        2023-08-18            20500          20500   
830263           2023-10-14        2024-10-13            86000          86000   
3242116          2021-09-01        2022-02-28            20000          40000   
5499457          2024-04-23        2025-04-22           110000         110000   

         no_of_prop  line_number  is_free_hold  ejari_bus_property_type_id  \
3054889           1            1           0.0                         2.0   
4033793           1            1           0.0                         2.0   
830263            1            1           1.0                         2.0   
3242116           1            1           0.0                         2.0   
5499457           1            1           1.0                         4.0   

        ejari_bus_property_type_en  ejari_property_type_id  \
3054889                       Unit                   842.0   
4033793                       Unit                   842.0   
830263                        Unit                   842.0   
3242116                       Unit                   842.0   
5499457                      Villa                   841.0   

        ejari_property_type_en  ejari_property_sub_type_id  \
3054889                   Flat                         2.0   
4033793                   Flat                        11.0   
830263                    Flat                         1.0   
3242116                   Flat                         1.0   
5499457                  Villa                         3.0   

        ejari_property_sub_type_en  project_number  \
3054889           2 bed rooms+hall             NaN   
4033793                     Studio             NaN   
830263              1bed room+Hall          1670.0   
3242116             1bed room+Hall             NaN   
5499457           3 bed rooms+hall          1621.0   

                    project_name_en master_project_en  area_id  \
3054889                         NaN               NaN    301.0   
4033793                         NaN               NaN    361.0   
830263              AL HABTOOR CITY               NaN    526.0   
3242116                         NaN               NaN    326.0   
5499457  DAMAC HILLS (2) - JANUSIA      DAMAC HILLS 2    505.0   

              area_name_en  actual_area          nearest_landmark_en  \
3054889    Al Nahda Second         74.0  Dubai International Airport   
4033793  Muhaisanah Fourth         50.0  Dubai International Airport   
830263        Business Bay         96.0               Downtown Dubai   
3242116   Um Hurair Second         68.0  Dubai International Airport   
5499457     Madinat Hind 4        152.0                          NaN   

                      nearest_metro_en     nearest_mall_en  tenant_type_id  \
3054889          STADIUM Metro Station  City Centre Mirdif             1.0   
4033793         Etisalat Metro Station  City Centre Mirdif             1.0   
830263      Business Bay Metro Station          Dubai Mall             1.0   
3242116  Healthcare City Metro Station          Dubai Mall             1.0   
5499457                            NaN                 NaN             1.0   

        tenant_type_en  
3054889         Person  
4033793         Person  
830263          Person  
3242116         Person  
5499457         Person

In [23]:
# Inspecting missing values percentages of the dataset
rent_contracts_residential_3y.isnull().sum() / rent_contracts_residential_3y.shape[0] * 100

contract_id                    0.000000
contract_reg_type_id           0.000000
contract_reg_type_en           0.000000
contract_start_date            0.000000
contract_end_date              0.000000
contract_amount                0.000000
annual_amount                  0.000000
no_of_prop                     0.000000
line_number                    0.000000
is_free_hold                   0.000000
ejari_bus_property_type_id     0.000000
ejari_bus_property_type_en     0.000000
ejari_property_type_id         0.003169
ejari_property_type_en         0.009989
ejari_property_sub_type_id     0.007141
ejari_property_sub_type_en     0.034982
project_number                78.527062
project_name_en               78.527062
master_project_en             56.528794
area_id                        0.000000
area_name_en                   0.000000
actual_area                    5.859585
nearest_landmark_en            7.861696
nearest_metro_en              14.791278
nearest_mall_en               15.202075


The current state of the rent contracts dataset looks promising for further analysis, with the following key observations:

1. **Project and Area Information**:

   - **Project Details**: The `project_number`, `project_name_en`, and `master_project_en` columns still show a high level of missing values (approximately 78% and 57%). We might consider if the remaining project-specific records provide enough value or decide to use more generalized area data for analysis.

   - **Area Details**: `area_id` and `area_name_en` are fully populated, ensuring geographical insights are intact for the dataset.

2. **Property and Usage Types**:

   - **Residential Properties**: By filtering for residential properties (`property_usage_en`), we have a focused dataset aligned with our objective to calculate rental yields and forecast residential market trends.
   - **Property Types**: Columns such as `ejari_property_type_id`, `ejari_property_type_en`, and `ejari_property_sub_type_en` show only minor gaps (about 0.3% to 3.5%), which should be manageable for further analysis. The dataset retains strong coverage of key property details, like whether the unit is a flat, villa, or specific configuration (e.g., studio, 1-bedroom).

3. **Tenant and Contract Type Information**:
   - **Tenant Type**: The `tenant_type_id` and `tenant_type_en` columns have around 7% missing data, which may require imputation or filtering if necessary for tenant analysis.
   - **Contract Type**: `contract_reg_type_en` and `contract_amount` are complete, providing a clear view of contract types (e.g., New or Renew) and rental amounts for each unit.

4. **Proximity to Amenities**:
   - **Nearest Amenities**: Some columns indicating the nearest landmarks, metro stations, and malls contain moderate missing values (around 8% to 15%). These can potentially be filled or marked as unavailable, depending on the significance of proximity data in our analysis.

5. **Area and Size**:
   - **Actual Area**: With only about 5.9% missing values, `actual_area` is well-populated, giving us a solid foundation for size-based calculations, such as rent per square foot, which is essential for accurate yield analysis.

This filtered and cleaned dataset aligns well with our objectives and is structured to support deeper analysis of residential rental yields, tenant behavior, and other key metrics relevant to the real estate market. Next, we can proceed with imputation, if needed, and begin to engineer features for our model.

In [24]:
# Inspecting "contract_id" uniqueness
unique_contracts = rent_contracts_residential_3y['contract_id'].nunique()
total_contracts = rent_contracts_residential_3y.shape[0]
print(f"Unique contract IDs: {unique_contracts} out of {total_contracts} total entries")
if unique_contracts == total_contracts:
    print("Each contract_id is unique.")
else:
    print(f"There are {total_contracts - unique_contracts} duplicate contract IDs.")

Unique contract IDs: 2079161 out of 2492719 total entries
There are 413558 duplicate contract IDs.


In [25]:
# Displaying random samples of duplicated contract_id observations
rent_contracts_residential_3y[rent_contracts_residential_3y.duplicated(subset='contract_id', keep=False)].head(10)

contract_id  contract_reg_type_id contract_reg_type_en  \
247628  CRT1352509366                     1                  New   
247629  CRT1352509366                     1                  New   
247939  CRT1353000496                     2                Renew   
247940  CRT1353000496                     2                Renew   
250293  CRT1356565156                     2                Renew   
250294  CRT1356565156                     2                Renew   
250295  CRT1356565156                     2                Renew   
250296  CRT1356565156                     2                Renew   
250297  CRT1356565156                     2                Renew   
250298  CRT1356565156                     2                Renew   

       contract_start_date contract_end_date  contract_amount  annual_amount  \
247628          2021-01-01        2021-12-31            28000          28000   
247629          2021-01-01        2021-12-31            28000          28000   
247939          2021-01-05        2022-01-04            19000          19000   
247940          2021-01-05        2022-01-04            19000          19000   
250293          2021-01-01        2021-12-31           561600         561600   
250294          2021-01-01        2021-12-31           561600         561600   
250295          2021-01-01        2021-12-31           561600         561600   
250296          2021-01-01        2021-12-31           561600         561600   
250297          2021-01-01        2021-12-31           561600         561600   
250298          2021-01-01        2021-12-31           561600         561600   

        no_of_prop  line_number  is_free_hold  ejari_bus_property_type_id  \
247628           1            1           1.0                         2.0   
247629           1            2           1.0                         2.0   
247939           1            1           1.0                         2.0   
247940           1            2           1.0                         2.0   
250293          26            1           1.0                         2.0   
250294          26            2           1.0                         2.0   
250295          26            3           1.0                         2.0   
250296          26            4           1.0                         2.0   
250297          26            5           1.0                         2.0   
250298          26            6           1.0                         2.0   

       ejari_bus_property_type_en  ejari_property_type_id  \
247628                       Unit                   842.0   
247629                       Unit                   842.0   
247939                       Unit                   842.0   
247940                       Unit                   842.0   
250293                       Unit                     4.0   
250294                       Unit                     4.0   
250295                       Unit                     4.0   
250296                       Unit                     4.0   
250297                       Unit                     4.0   
250298                       Unit                     4.0   

       ejari_property_type_en  ejari_property_sub_type_id  \
247628                   Flat                         1.0   
247629                   Flat                         1.0   
247939                   Flat                        11.0   
247940                   Flat                        11.0   
250293            Labor Camps                        12.0   
250294            Labor Camps                        12.0   
250295            Labor Camps                        12.0   
250296            Labor Camps                        12.0   
250297            Labor Camps                        12.0   
250298            Labor Camps                        12.0   

       ejari_property_sub_type_en  project_number            project_name_en  \
247628             1bed room+Hall           333.0  ELITE II SPORTS RESIDENCE   
247629             1bed room

In [26]:
# Identifying duplicate `contract_id` rows
duplicate_contract_ids = rent_contracts_residential_3y[rent_contracts_residential_3y.duplicated(subset='contract_id', keep=False)]

# Checking if each duplicate `contract_id` has unique `line_number` values
unique_line_number_check = duplicate_contract_ids.groupby('contract_id')['line_number'].nunique()

# Confirming all duplicates have unique line_number values per contract_id
all_unique_line_numbers = unique_line_number_check.eq(unique_line_number_check)

# Displaying a summary
print(all_unique_line_numbers.value_counts())

line_number
True    37822
Name: count, dtype: int64


The presence of duplicates in `contract_id` with different `line_number` values indicates that each `line_number` within a `contract_id` represents a distinct property or unit associated with that single contract. Essentially, a contract ID can cover multiple properties, each listed as a separate “line” or entry under the same contract ID. Here’s what this tells us:

1. **Multi-Property Contracts**: Each duplicate `contract_id` with a unique `line_number` shows that a single contract might include multiple properties or units (like multiple apartments or rooms within a building rented under one agreement).

2. **Granularity**: This `line_number` column allows us to differentiate between individual properties within the same contract, making the data more granular. Each line provides a breakdown of the contract at the property level.


Let's inspecting the Contract Registration Type Columns

In [27]:
# Displaying the value counts of the registration types
print("Unique Value Count of 'contract_reg_type_id':")
print(rent_contracts_residential_3y['contract_reg_type_id'].value_counts())

print("\nUnique Value Count of 'contract_reg_type_en':")
print(rent_contracts_residential_3y['contract_reg_type_en'].value_counts())


Unique Value Count of 'contract_reg_type_id':
contract_reg_type_id
2    1258228
1    1234491
Name: count, dtype: int64

Unique Value Count of 'contract_reg_type_en':
contract_reg_type_en
Renew    1258228
New      1234491
Name: count, dtype: int64


The counts for both contract_reg_type_id and contract_reg_type_en indicate two distinct types of contracts:

- **Renew (Type 2)**: 1,258,228 contracts

- **New (Type 1)**: 1,234,491 contracts

This alignment between the `contract_reg_type_id` and `contract_reg_type_en` values confirms that each contract type is consistently categorized across both columns, with no discrepancies.

Let's inspect the `contract_start_date` and `contract_end_date`

In [28]:
# Statistical summary of the contract_start_date & contract_end_date columns
print(rent_contracts_residential_3y[['contract_start_date', 'contract_end_date']].describe())

                 contract_start_date              contract_end_date
count                        2492719                        2492719
mean   2022-12-30 04:58:34.128950016  2024-01-10 13:19:02.813290496
min              2021-01-01 00:00:00            2021-01-31 00:00:00
25%              2022-01-20 00:00:00            2023-01-31 00:00:00
50%              2023-01-10 00:00:00            2024-01-15 00:00:00
75%              2023-12-10 00:00:00            2024-12-15 00:00:00
max              2204-10-04 00:00:00            2205-10-03 00:00:00


Upon examining the `contract_start_date` and `contract_end_date` fields, we discovered some extreme future dates extending as far as **2204** and **2205**. These outliers likely result from data entry errors, as they significantly deviate from realistic contract durations and our focus on recent years.



In [29]:
# Importing datetime
from datetime import datetime, timedelta

# Shape of data before filtering
print("Rent Contracts Residential Shape Before Filtering:", rent_contracts_residential_3y.shape)

# Get the current year
current_year = datetime.now().year

# Define the target years dynamically for the last three years
target_years = [current_year - 3, current_year - 2, current_year - 1, current_year, current_year + 1]

# Apply the filter based on contract start date falling within these years
rent_contracts_residential_3y = rent_contracts_residential_3y[
    rent_contracts_residential_3y['contract_start_date'].dt.year.isin(target_years)
]

# Shape of data after filtering
print("Rent Contracts Residential Shape After Filtering:", rent_contracts_residential_3y.shape)

Rent Contracts Residential Shape Before Filtering: (2492719, 27)
Rent Contracts Residential Shape After Filtering: (2492673, 27)


In [30]:
# Statistical summary of the contract_start_date & contract_end_date columns
print(rent_contracts_residential_3y[['contract_start_date', 'contract_end_date']].describe())

                 contract_start_date              contract_end_date
count                        2492673                        2492673
mean   2022-12-30 02:51:56.674508032  2024-01-10 10:58:30.568776448
min              2021-01-01 00:00:00            2021-01-31 00:00:00
25%              2022-01-20 00:00:00            2023-01-31 00:00:00
50%              2023-01-10 00:00:00            2024-01-15 00:00:00
75%              2023-12-10 00:00:00            2024-12-15 00:00:00
max              2025-12-31 00:00:00            2034-10-09 00:00:00


Now, we see:

- **Contract Start Date**: Ranges from **2021-01-01** to **2024-12-31**, capturing data within the last three years.

- **Contract End Date**: Has a max value extending up to **2034-10-09**, allowing for long-term contracts without excluding multi-year agreements that began within the last three years.


In [31]:
# Displaying random observations from the dataset
rent_contracts_residential_3y.sample(5)

contract_id  contract_reg_type_id contract_reg_type_en  \
2938005  CNT1406599816                     1                  New   
945275   CRT2117047246                     2                Renew   
5727751  CNT2117463635                     2                Renew   
5571309  CNT2113670843                     1                  New   
4710224  CNT2082695110                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
2938005          2021-03-18        2022-04-16            24000          24000   
945275           2023-12-10        2024-12-09            30450          30450   
5727751          2024-08-01        2025-07-31            65000          65000   
5571309          2024-05-01        2025-04-30            32640          32640   
4710224          2023-04-16        2024-04-15            38710          38710   

         no_of_prop  line_number  is_free_hold  ejari_bus_property_type_id  \
2938005           1            1           1.0                         2.0   
945275            1            1           1.0                         2.0   
5727751           1            1           1.0                         2.0   
5571309           4            1           0.0                         2.0   
4710224           1            1           1.0                         2.0   

        ejari_bus_property_type_en  ejari_property_type_id  \
2938005                       Unit                   842.0   
945275                        Unit                   842.0   
5727751                       Unit                   842.0   
5571309                       Unit                     4.0   
4710224                       Unit                   842.0   

        ejari_property_type_en  ejari_property_sub_type_id  \
2938005                   Flat                        11.0   
945275                    Flat                        11.0   
5727751                   Flat                         2.0   
5571309            Labor Camps                        12.0   
4710224                   Flat                         1.0   

        ejari_property_sub_type_en  project_number  project_name_en  \
2938005                     Studio             NaN              NaN   
945275                      Studio          1689.0  BINGHATTI VIEWS   
5727751           2 bed rooms+hall             NaN              NaN   
5571309         Room in labor Camp             NaN              NaN   
4710224             1bed room+Hall             NaN              NaN   

                           master_project_en  area_id  \
2938005                          The Gardens    445.0   
945275                         Silicon Oasis    484.0   
5727751                                  NaN    232.0   
5571309                                  NaN    395.0   
4710224  International Media Production Zone    485.0   

                       area_name_en  actual_area  \
2938005             Jabal Ali First         43.0   
945275                   Nadd Hessa         45.0   
5727751                      Mirdif        141.0   
5571309  Jabal Ali Industrial First         15.0   
4710224              Me'Aisem First         91.0   

                  nearest_landmark_en           nearest_metro_en  \
2938005  Sports City Swimming Academy  Ibn Battuta Metro Station   
945275           IMG World Adventures                        NaN   
5727751   Dubai International Airport    Rashidiya Metro Station   
5571309                Expo 2020 Site       DANUBE Metro Station   
4710224  Sports City Swimming Academy           Damac Properties   

            nearest_mall_en  tenant_type_id tenant_type_en  
2938005  Ibn-e-Battuta Mall             1.0         Person  
945275                  NaN             1.0         Person  
5727751  City Centre Mirdif             1.0         Person  
5571309  Ibn-e-Battuta Mall             2.0      Authority  
4710224         Marina Mall             1.0         Person

Let's inspect the `no_of_prop` column

In [32]:
# Unique values count of "no_of_prop" column
rent_contracts_residential_3y['no_of_prop'].value_counts()[:]

no_of_prop
1      2043919
2        19833
3        15283
5        14599
10       13926
4        13856
6        11150
8         9207
20        9165
7         9115
15        8676
12        7032
30        6927
9         6692
40        6516
90        6390
25        6270
13        5771
14        5162
32        5025
11        4962
17        4454
22        4442
18        4393
50        4343
16        4282
23        4074
21        4065
60        3899
28        3824
24        3816
46        3355
100       3300
80        3281
36        3154
27        2913
35        2888
45        2880
44        2813
19        2809
33        2801
38        2774
70        2730
66        2706
29        2566
48        2550
26        2543
52        2496
42        2394
41        2377
88        2376
53        2226
72        2160
34        2151
64        2108
62        2107
31        2099
37        2035
65        2015
55        1923
120       1919
58        1914
47        1879
264       1848
56        1800
160       1760

- To ensure our analysis remains focused on residential rental trends, we have decided to filter the data to include only contracts where:

	- `no_of_prop` is equal to 1, indicating that each contract involves a single rented unit.

	- `line_number` is also equal to 1, which ensures we’re capturing only the primary unit details for each contract.

- This approach allows us to:

	- **Exclude multi-unit and labor camp rentals**: By filtering out contracts with multiple properties, we avoid the influence of large-scale rental agreements, such as labor camps or commercial leases, which could skew our insights.

	- **Focus on individual residential units**: Each remaining contract will represent a unique residential unit, helping us to directly observe rental patterns and pricing trends specific to individual residential properties.

	- **Improve data clarity for rental trend analysis**: With this filter applied, our analysis will better reflect the true residential rental market trends, providing meaningful insights aligned with our project’s objectives.

In [33]:
# Filtering rent contracts to include only a single property per contract
rent_contracts_residential_single_prop_3y = rent_contracts_residential_3y[rent_contracts_residential_3y['no_of_prop'] == 1]

# Comparing shapes before and after filtering
print("Rent Contracts Residential Before Filtering:", rent_contracts_residential_3y.shape)
print("Rent Contracts Residential After Filtering:", rent_contracts_residential_single_prop_3y.shape)

Rent Contracts Residential Before Filtering: (2492673, 27)
Rent Contracts Residential After Filtering: (2043919, 27)


Let's inspect the `line_number` column

In [34]:
# Unique value count of line_number column
rent_contracts_residential_single_prop_3y['line_number'].value_counts()

line_number
1    2042556
2       1363
Name: count, dtype: int64

Despite this filter, we observed that some contracts still contain multiple entries, indicated by `line_number` values greater than 1. These secondary lines likely represent administrative adjustments rather than separate units, given that `no_of_prop` equals 1. To further refine our dataset, we’ll now filter for `line_number == 1`, ensuring that only primary contract lines are retained

In [35]:
# Filtering rent contracts to include only the first line number per contract
rent_contracts_residential_single_prop_first_line_3y = rent_contracts_residential_single_prop_3y[
    rent_contracts_residential_single_prop_3y['line_number'] == 1
]

# Comparing shapes before and after filtering
print("Rent Contracts Residential Single Prop Before Filtering:", rent_contracts_residential_single_prop_3y.shape)
print("Rent Contracts Residential Single Prop After Filtering:", rent_contracts_residential_single_prop_first_line_3y.shape)

Rent Contracts Residential Single Prop Before Filtering: (2043919, 27)
Rent Contracts Residential Single Prop After Filtering: (2042556, 27)


In [36]:
# Removing no_of_prop & line_number columns from the dataset
rent_contracts_residential_single_prop_first_line_3y = rent_contracts_residential_single_prop_first_line_3y.drop(columns=['line_number', 'no_of_prop'])

# Inspecting shape of data
print(rent_contracts_residential_single_prop_first_line_3y.shape)

(2042556, 25)


In [37]:
# Displaying random observations from the dataset
print(rent_contracts_residential_single_prop_first_line_3y.sample(5))

           contract_id  contract_reg_type_id contract_reg_type_en  \
4710631  CNT2082703742                     2                Renew   
569646   CRT1940330076                     1                  New   
3024706  CNT1440139705                     1                  New   
387733   CRT1612284806                     1                  New   
3650653  CNT1842837412                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
4710631          2023-03-22        2024-03-21           104000         104000   
569646           2022-06-01        2023-05-31           115000         115000   
3024706          2021-04-28        2022-04-27            40000          40000   
387733           2021-07-01        2022-06-30            26666          26666   
3650653          2021-12-13        2022-12-12            26000          26000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
4710631           

Let's inspect the `is_free_hold` column

In [38]:
# Unique value count of "is_free_hold" column
rent_contracts_residential_single_prop_first_line_3y['is_free_hold'].value_counts()

is_free_hold
1.0    1102834
0.0     939722
Name: count, dtype: int64

In [39]:
# Group by is_free_hold and calculate average contract and annual amounts
print(rent_contracts_residential_single_prop_first_line_3y.groupby('is_free_hold').agg(
    count_contracts=('contract_amount', 'count'),
    avg_contract_amount=('contract_amount', 'mean'),
    avg_annual_amount=('annual_amount', 'mean')
    
))

              count_contracts  avg_contract_amount  avg_annual_amount
is_free_hold                                                         
0.0                    939722         64046.785953       63620.473497
1.0                   1102834         83053.780991       82337.823907


Our analysis of UAE rental contracts reveals a notable distinction between freehold and non-freehold properties, both in count and rental pricing. In our dataset, there are 1,102,429 contracts for freehold properties and 939,189 for non-freehold properties. The average rental amounts are significantly higher for freehold properties, with contract and annual amounts averaging approximately 83,000 AED and 82,000 AED, respectively, compared to around 64,000 AED and 63,000 AED for non-freehold rentals.

This difference aligns with the benefits of freehold properties in the UAE, where landlords retain full ownership and more flexibility in maintenance and modifications, potentially increasing desirability and rental value. This insight underscores a premium trend in the UAE rental market, where freehold properties offer both tenants and landlords enhanced long-term value and appeal.

In [40]:
# Displaying random observations from the dataset
display(rent_contracts_residential_single_prop_first_line_3y.sample(5))

contract_id  contract_reg_type_id contract_reg_type_en  \
5904085  CNT2122205077                     2                Renew   
5309685  CNT2107539857                     2                Renew   
4433898  CNT2062684295                     1                  New   
4400421  CNT2057660244                     2                Renew   
4078426  CNT1985613928                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
5904085          2024-10-10        2025-10-09            52000          52000   
5309685          2024-02-03        2025-02-02            58000          58000   
4433898          2023-01-01        2023-06-30            23100          46200   
4400421          2023-01-17        2024-01-16            56000          56000   
4078426          2022-09-01        2023-08-31            66000          66000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
5904085           0.0                         2.0                       Unit   
5309685           0.0                         2.0                       Unit   
4433898           0.0                         2.0                       Unit   
4400421           0.0                         2.0                       Unit   
4078426           1.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
5904085                   842.0                   Flat   
5309685                   842.0                   Flat   
4433898                   842.0                   Flat   
4400421                   842.0                   Flat   
4078426                   842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
5904085                         2.0           2 bed rooms+hall   
5309685                         2.0           2 bed rooms+hall   
4433898                         2.0           2 bed rooms+hall   
4400421                         2.0           2 bed rooms+hall   
4078426                         2.0           2 bed rooms+hall   

         project_number project_name_en master_project_en  area_id  \
5904085             NaN             NaN               NaN    305.0   
5309685             NaN             NaN               NaN    342.0   
4433898             NaN             NaN               NaN    297.0   
4400421             NaN             NaN               NaN    355.0   
4078426             NaN             NaN      TECOM Site C    443.0   

                         area_name_en  actual_area  \
5904085               Al Qusais First         62.0   
5309685  Ras Al Khor Industrial Third        127.0   
4433898                Al Warqa First         91.0   
4400421                Al Nahda First        144.0   
4078426              Al Thanyah First         90.0   

                 nearest_landmark_en         nearest_metro_en  \
5904085  Dubai International Airport   Al Nahda Metro Station   
5309685  Dubai International Airport  Rashidiya Metro Station   
4433898  Dubai International Airport  Rashidiya Metro Station   
4400421  Dubai International Airport    STADIUM Metro Station   
4078426                 Burj Al Arab      Dubai Internet City   

              nearest_mall_en  tenant_type_id tenant_type_en  
5904085    City Centre Mirdif             1.0         Person  
5309685    City Centre Mirdif             1.0         Person  
4433898    City Centre Mirdif             1.0         Person  
4400421    City Centre Mirdif             1.0         Person  
4078426  Mall of the Emirates             1.0         Person

To streamline our analysis, we’ll examine four columns in the rent contracts dataset that outline the property type at different levels of hierarchy. These columns provide multiple layers of categorization, starting from broad classifications to more specific property descriptions.

- **Ejari Bus Property Type ID and Ejari Bus Property Type EN**: These columns represent the broadest classification, distinguishing between primary property types such as Unit, Villa, Land, and possibly other categories. This high-level classification provides an overview of the general property type.

- **Ejari Property Type ID and Ejari Property Type EN**: These columns break down the Ejari Bus Property Type into more detailed subcategories, specifying property types like Flat, Villa, and other specific property types. This further categorization allows for a more nuanced view within each broad property class.

By analyzing these columns together, we aim to identify the relationships between these property types, ensuring that each higher-level category logically includes its relevant subcategories. Additionally, understanding these hierarchies will aid in filtering and grouping property types, which will be essential as we calculate metrics and generate insights from the data.

Let’s start by examining the unique values and relationships within these columns to establish the hierarchy and check for consistency.

In [41]:
# Displaying unique value counts for the "ejari_bus_property_type" columns & "ejari_property_type" columns
print("Unique Value Count of 'ejari_bus_property_type_id':")
print(rent_contracts_residential_single_prop_first_line_3y['ejari_bus_property_type_id'].value_counts(dropna=False))

print("\nUnique Value Count of 'ejari_bus_property_type_en':")
print(rent_contracts_residential_single_prop_first_line_3y['ejari_bus_property_type_en'].value_counts(dropna=False))

print("\nUnique Value Count of 'ejari_property_type_id':")
print(rent_contracts_residential_single_prop_first_line_3y['ejari_property_type_id'].value_counts(dropna=False))

print("\nUnique Value Count of 'ejari_property_type_en':")
print(rent_contracts_residential_single_prop_first_line_3y['ejari_property_type_en'].value_counts(dropna=False))

Unique Value Count of 'ejari_bus_property_type_id':
ejari_bus_property_type_id
2.0    1814109
4.0     223314
5.0       4873
1.0        181
0.0         79
Name: count, dtype: int64

Unique Value Count of 'ejari_bus_property_type_en':
ejari_bus_property_type_en
Unit            1814109
Villa            223314
Virtual Unit       4873
Building            181
Land                 79
Name: count, dtype: int64

Unique Value Count of 'ejari_property_type_id':
ejari_property_type_id
842.0          1766639
841.0           205414
903.0            27724
4.0              22436
19.0             18075
985.0              612
844.0              505
923.0              386
10.0               174
0.0                168
24.0               145
352361946.0         90
NaN                 79
12.0                46
608333806.0         44
9.0                  8
1.0                  8
2.0                  3
Name: count, dtype: int64

Unique Value Count of 'ejari_property_type_en':
ejari_property_type_en
Flat      

Here’s a breakdown of the findings and suggested steps to enhance data quality and alignment with the analysis objectives:

1. **Ejari Bus Property Type Level**:
	
    - **Dominant Property Type**: **“Unit”** (**1,813,299** entries) is the most frequent type, followed by **“Villa”** (**223,187**), showing that standard residential units dominate the rental data in urban areas like Dubai.

	- **Less Common Types**: **“Virtual Unit”** (**4,872** entries), **“Building”** (**181**), and **“Land”** (**79**) are infrequent, aligning with expectations for urban rentals but possibly less relevant for standard residential rental analysis.

	- **Missing Data**: No missing values are detected here, but the low counts for **“Building”** and **“Land”** suggest minimal relevance for a residential-focused analysis.

2. **Ejari Property Type Level**:

	- **Main Categories**: **“Flat”** (**1,765,838** entries) and **“Villa”** (**205,301** entries) are predominant, which corresponds well with the general **“Unit”** and **“Villa”** categories in the **Ejari Bus Property Type** level. Other frequent entries, such as **“Studio”** and **“Labor Camps,”** provide additional granularity but may not align directly with residential-focused analysis.

	- **Niche Categories**: Some specialized property types, like **“Complex Villas,”** **“Staff Accommodation,”** **“Penthouse,”** and **“Portacabin,”** are less frequent. These categories may be relevant for specific use cases but could dilute insights focused on standard rentals.

	- **Erroneous and Missing Values**: Some `ejari_property_type_id` entries, such as **352361946.0** and **608333806.0**, suggest data entry errors. Additionally, NaN values in both `ejari_property_type_id` and `ejari_property_type_en` may require handling to avoid gaps in analysis. These values may be grouped under an **“Unknown”** or **“Other”** category if imputation is not viable.

3. **Alignment and Cleaning Recommendations**:

	- **Data Standardization**: To streamline the data for residential analysis, it may be beneficial to combine less common or niche categories (e.g., **“Labor Camps,”** **“Staff Accommodation,”** and **“Portacabin”**) under an **“Other”** or **“Non-Residential”** label, ensuring data remains relevant and interpretable.

	- **Error Handling**: Erroneous entries in `ejari_property_type_id` should be filtered or corrected to ensure data quality. Missing values, particularly in `ejari_property_type_id` and `ejari_property_type_en`, could be either imputed or grouped to prevent loss of context in analysis.

4. **Hierarchy Consolidation**:

	- **Unified Property Type Feature**: Developing a single consolidated property type feature by mapping `ejari_bus_property_type_id` and `ejari_property_type_id` into simplified residential categories (e.g., **“Apartment,”** **“Villa,”** **“Commercial”**) can facilitate more cohesive analysis and provide clear distinctions for financial modeling.


To focus our analysis on the relevant residential property types, we’ll filter the `ejari_bus_property_type_en` to include only **“Unit”** and **“Villa.”** This way, we align the rent contracts data with the transactions data, honing in on residential rentals.

In [42]:
# Filter the rent contracts data to include only residential property types
rent_contracts_unit_villa = rent_contracts_residential_single_prop_first_line_3y[
    rent_contracts_residential_single_prop_first_line_3y['ejari_bus_property_type_en'].isin(['Unit', 'Villa'])
]

# Comparing shapes before and after filtering
print("Rent Contracts Before Filtering:", rent_contracts_residential_single_prop_first_line_3y.shape)
print("Rent Contracts After Filtering:", rent_contracts_unit_villa.shape)

Rent Contracts Before Filtering: (2042556, 25)
Rent Contracts After Filtering: (2037423, 25)


In [43]:
# Displaying the unique values count in the "ejari_property_type_en"
rent_contracts_unit_villa.groupby("ejari_bus_property_type_en")['ejari_property_type_en'].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en
Unit                        Flat                      1765271
                            Studio                      27719
                            Labor Camps                 19135
                            Villa                         578
                            Building                      388
                            Staff Accommodation           244
                            Mezzanine                     174
                            Arabian House                 159
                            NaN                           145
                            Hotel                         124
                            Penthouse                      90
                            Portacabin                     44
                            Complex Villas                 16
                            Shop                            8
                            Store                           8
                   

1. **Dominant Property Types**:

	- **Units** are predominantly **“Flat”** (**1,764,471** entries), followed by **“Studio”** (**27,713** entries) and **“Labor Camps”** (**19,134** entries).

	- **Villas** primarily appear as **“Villa”** (**204,723** entries), with a smaller presence in **“Complex Villas”** (**18,045** entries) and a few unique entries in **“Villa addendum”** (**43** entries).

2. **Irrelevant Property Types for Residential Analysis**:

	- Entries such as **“Labor Camps”**, **“Portacabin”**, **“Staff Accommodation”**, and **“Office”** under the **“Unit”** category do not fit the residential scope and could be excluded from further analysis.

	- While these property types are interesting as outliers, their presence is minor and not aligned with standard residential rental analysis, so we might consider filtering them out.

3. **Missing Data**:

	- There is a small number of missing values in `ejari_property_type_en` (**144** entries under **“Unit”** and **23** under **“Villa”**).

	- This is manageable but worth addressing, possibly through imputation or removal, depending on the overall impact on analysis quality.

First, I'd like to investigate the values where the `ejari_bus_property_type_en` is "Villa" and the `ejari_property_type_en` is "Flat".

In [44]:
# Displaying the shaoe where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Flat"
rent_contracts_unit_villa[
    (rent_contracts_unit_villa['ejari_bus_property_type_en'] == 'Villa') & 
    (rent_contracts_unit_villa['ejari_property_type_en'] == 'Flat')
].shape 

(100, 25)

In [45]:
# Displaying random osbervations where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Flat"
rent_contracts_unit_villa[
    (rent_contracts_unit_villa['ejari_bus_property_type_en'] == 'Villa') & 
    (rent_contracts_unit_villa['ejari_property_type_en'] == 'Flat')
].sample(5)

contract_id  contract_reg_type_id contract_reg_type_en  \
5188153  CNT2104337581                     2                Renew   
3177786  CNT1524489810                     2                Renew   
5871193  CNT2121726771                     2                Renew   
3875490  CNT1916515407                     2                Renew   
4841093  CNT2088084687                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
5188153          2023-12-20        2024-12-19            85878          85878   
3177786          2021-09-06        2022-09-05           132528         132528   
5871193          2024-08-20        2025-08-19           340000         340000   
3875490          2022-07-01        2024-06-30           480000         240000   
4841093          2023-09-15        2024-09-14           330000         330000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
5188153           1.0                         4.0                      Villa   
3177786           1.0                         4.0                      Villa   
5871193           0.0                         4.0                      Villa   
3875490           0.0                         4.0                      Villa   
4841093           0.0                         4.0                      Villa   

         ejari_property_type_id ejari_property_type_en  \
5188153                   842.0                   Flat   
3177786                   842.0                   Flat   
5871193                   842.0                   Flat   
3875490                   842.0                   Flat   
4841093                   842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
5188153                         2.0           2 bed rooms+hall   
3177786                         4.0           4 bed rooms+hall   
5871193                         5.0           5 bed rooms+hall   
3875490                         5.0           5 bed rooms+hall   
4841093                         5.0           5 bed rooms+hall   

         project_number project_name_en master_project_en  area_id  \
5188153             NaN             NaN               NaN    232.0   
3177786             NaN             NaN               NaN    232.0   
5871193             NaN             NaN               NaN    317.0   
3875490             NaN             NaN               NaN    317.0   
4841093             NaN             NaN               NaN    317.0   

           area_name_en  actual_area          nearest_landmark_en  \
5188153          Mirdif          0.0  Dubai International Airport   
3177786          Mirdif          0.0  Dubai International Airport   
5871193  Jumeirah First        465.0                 Burj Khalifa   
3875490  Jumeirah First        465.0                 Burj Khalifa   
4841093  Jumeirah First        465.0                 Burj Khalifa   

                             nearest_metro_en     nearest_mall_en  \
5188153               Rashidiya Metro Station  City Centre Mirdif   
3177786               Rashidiya Metro Station  City Centre Mirdif   
5871193  Buj Khalifa Dubai Mall Metro Station          Dubai Mall   
3875490  Buj Khalifa Dubai Mall Metro Station          Dubai Mall   
4841093  Buj Khalifa Dubai Mall Metro Station          Dubai Mall   

         tenant_type_id tenant_type_en  
5188153             1.0         Person  
3177786             1.0         Person  
5871193             1.0         Person  
3875490             1.0         Person  
4841093             1.0         Person

In [46]:
# Displaying contract_amount statistics where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Flat"
rent_contracts_unit_villa[
    (rent_contracts_unit_villa['ejari_bus_property_type_en'] == 'Villa') & 
    (rent_contracts_unit_villa['ejari_property_type_en'] == 'Flat')
]['contract_amount'].describe()

count       100.000000
mean     180779.660000
std       98334.962672
min        3000.000000
25%       84750.000000
50%      145914.000000
75%      272318.750000
max      480000.000000
Name: contract_amount, dtype: float64

In [47]:
# Displaying ejari_property_sub_type_en value count where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Flat"
rent_contracts_unit_villa[
    (rent_contracts_unit_villa['ejari_bus_property_type_en'] == 'Villa') & 
    (rent_contracts_unit_villa['ejari_property_type_en'] == 'Flat')
]['ejari_property_sub_type_en'].value_counts(dropna=False)

ejari_property_sub_type_en
5 bed rooms+hall    40
2 bed rooms+hall    29
4 bed rooms+hall    23
6 bed rooms+hall     4
3 bed rooms+hall     3
1bed room+Hall       1
Name: count, dtype: int64

In [48]:
# Displaying unique value counts for "ejari_property_type_en" column
rent_contracts_unit_villa['ejari_property_type_en'].value_counts(dropna=False)

ejari_property_type_en
Flat                   1765371
Villa                   205414
Studio                   27724
Labor Camps              19135
Complex Villas           18075
Building                   388
Arabian House              386
Staff Accommodation        244
Mezzanine                  174
NaN                        168
Hotel                      145
Penthouse                   90
Villa addendum              46
Portacabin                  44
Store                        8
Shop                         8
Office                       3
Name: count, dtype: int64

In [49]:
# Displaying random observations where bus property type is "Unit" & property type is null
display(rent_contracts_unit_villa[
    (rent_contracts_unit_villa['ejari_bus_property_type_en'] == 'Unit') & rent_contracts_unit_villa['ejari_property_type_en'].isna()
].sample(5))

contract_id  contract_reg_type_id contract_reg_type_en  \
5875823  CNT2121747682                     1                  New   
5770777  CNT2118325188                     1                  New   
4320711  CNT2044004415                     2                Renew   
4914103  CNT2091512310                     1                  New   
5385226  CNT2109070280                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
5875823          2024-09-10        2025-09-09           350000         350000   
5770777          2024-08-01        2025-07-31            65000          65000   
4320711          2023-02-01        2024-01-31            55000          55000   
4914103          2023-09-05        2024-09-04            52000          52000   
5385226          2024-02-07        2025-02-06           125000         125000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
5875823           1.0                         2.0                       Unit   
5770777           1.0                         2.0                       Unit   
4320711           1.0                         2.0                       Unit   
4914103           1.0                         2.0                       Unit   
5385226           1.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
5875823                     0.0                    NaN   
5770777                     0.0                    NaN   
4320711                     0.0                    NaN   
4914103                     0.0                    NaN   
5385226                     0.0                    NaN   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
5875823                         0.0                        NaN   
5770777                         0.0                        NaN   
4320711                         0.0                        NaN   
4914103                         0.0                        NaN   
5385226                         0.0                        NaN   

         project_number            project_name_en   master_project_en  \
5875823          1937.0                 PARK RIDGE  DUBAI HILLS - PARK   
5770777          1810.0  Azizi Farishta Residence            Al Furjan   
4320711          1772.0              CREEK HORIZON         The Lagoons   
4914103          1810.0  Azizi Farishta Residence            Al Furjan   
5385226          1642.0             DOWNTOWN VIEWS                 NaN   

         area_id                       area_name_en  actual_area  \
5875823    482.0  Hadaeq Sheikh Mohammed Bin Rashid        191.0   
5770777    445.0                    Jabal Ali First         75.0   
4320711    447.0                   Al Khairan First         70.0   
4914103    445.0                    Jabal Ali First         75.0   
5385226    332.0                     Zaabeel Second         82.0   

                 nearest_landmark_en                      nearest_metro_en  \
5875823                 Burj Al Arab    First Abu Dhabi Bank Metro Station   
5770777               Expo 2020 Site             Ibn Battuta Metro Station   
4320711  Dubai International Airport                   Creek Metro Station   
4914103               Expo 2020 Site             Ibn Battuta Metro Station   
5385226                 Burj Khalifa  Buj Khalifa Dubai Mall Metro Station   

              nearest_mall_en  tenant_type_id tenant_type_en  
5875823  Mall of the Emirates             1.0         Person  
5770777    Ibn-e-Battuta Mall             1.0         Person  
4320711    City Centre Mirdif             1.0         Person  
4914103    Ibn-e-Battuta Mall             1.0         Person  
5385226            Dubai Mall             2.0      Authority

In [50]:
# Displaying random observations where bus property type is "Villa" & property type is null
display(rent_contracts_unit_villa[
    (rent_contracts_unit_villa['ejari_bus_property_type_en'] == 'Villa') & rent_contracts_unit_villa['ejari_property_type_en'].isna()
].sample(10))

contract_id  contract_reg_type_id contract_reg_type_en  \
4903870  CNT2091056900                     1                  New   
3041690  CNT1447218861                     2                Renew   
2907248  CNT1393988834                     2                Renew   
3655947  CNT1844629779                     2                Renew   
4789077  CNT2085890766                     2                Renew   
3186260  CNT1529298125                     1                  New   
4761364  CNT2084624145                     2                Renew   
5499590  CNT2112264915                     2                Renew   
4192216  CNT2011687633                     1                  New   
4433324  CNT2062633479                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
4903870          2023-08-22        2024-08-21           195000         195000   
3041690          2021-05-18        2022-05-17           155000         155000   
2907248          2021-01-01        2021-12-31           130000         130000   
3655947          2022-01-01        2022-12-31           125000         125000   
4789077          2023-06-15        2024-06-14            90000          90000   
3186260          2021-08-01        2022-07-31           130000         130000   
4761364          2023-05-25        2024-05-24           120000         120000   
5499590          2024-05-01        2025-04-30           194250         194250   
4192216          2022-10-26        2023-10-25            95000          95000   
4433324          2023-01-01        2023-12-31           125000         125000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
4903870           1.0                         4.0                      Villa   
3041690           1.0                         4.0                      Villa   
2907248           0.0                         4.0                      Villa   
3655947           0.0                         4.0                      Villa   
4789077           1.0                         4.0                      Villa   
3186260           1.0                         4.0                      Villa   
4761364           1.0                         4.0                      Villa   
5499590           1.0                         4.0                      Villa   
4192216           1.0                         4.0                      Villa   
4433324           0.0                         4.0                      Villa   

         ejari_property_type_id ejari_property_type_en  \
4903870                     0.0                    NaN   
3041690                     0.0                    NaN   
2907248                     0.0                    NaN   
3655947                     0.0                    NaN   
4789077                     0.0                    NaN   
3186260                     0.0                    NaN   
4761364                     0.0                    NaN   
5499590                     0.0                    NaN   
4192216                     0.0                    NaN   
4433324                     0.0                    NaN   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
4903870                         0.0                        NaN   
3041690                         0.0                        NaN   
2907248                         3.0           3 bed rooms+hall   
3655947                         3.0           3 bed rooms+hall   
4789077                         3.0           3 bed rooms+hall   
3186260                         0.0                        NaN   
4761364                         0.0                        NaN   
5499590                         3.0           3 bed rooms+hall   
4192216                         0.0                        NaN   
4433324                         3.0           3 bed rooms+hall   

         project_number              project_name_en  \
4903870          1832.0       AR II - Reem Community   


In [51]:
rent_contracts_unit_villa[['ejari_bus_property_type_id', 'ejari_bus_property_type_en']].value_counts()

ejari_bus_property_type_id  ejari_bus_property_type_en
2.0                         Unit                          1814109
4.0                         Villa                          223314
Name: count, dtype: int64

In [52]:
rent_contracts_unit_villa[['ejari_property_type_id', 'ejari_property_type_en']].value_counts()

ejari_property_type_id  ejari_property_type_en
842.0                   Flat                      1765371
841.0                   Villa                      205414
903.0                   Studio                      27724
4.0                     Labor Camps                 19135
19.0                    Complex Villas              18075
844.0                   Building                      388
923.0                   Arabian House                 386
985.0                   Staff Accommodation           244
10.0                    Mezzanine                     174
24.0                    Hotel                         145
352361946.0             Penthouse                      90
12.0                    Villa addendum                 46
608333806.0             Portacabin                     44
1.0                     Shop                            8
9.0                     Store                           8
2.0                     Office                          3
Name: count, dtype: int64

In [53]:
rent_contracts_unit_villa[['ejari_property_sub_type_id', 'ejari_property_sub_type_en']].value_counts()

ejari_property_sub_type_id  ejari_property_sub_type_en 
1.0                         1bed room+Hall                 712095
2.0                         2 bed rooms+hall               627198
11.0                        Studio                         330175
3.0                         3 bed rooms+hall               229233
4.0                         4 bed rooms+hall                78137
5.0                         5 bed rooms+hall                30534
12.0                        Room in labor Camp              18080
6.0                         6 bed rooms+hall                 5844
7.0                         7 bed rooms+hall                 1437
8.0                         8 bed rooms+hall                  986
35.0                        Duplex                            550
10.0                        10 bed rooms+hall                 460
422.0                       Office                            452
38.0                        Labor Camp                        394
621.0               

In [54]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
rent_contracts_unit_villa.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709938
                                                    2 bed rooms+hall               609748
                                                    Studio                         302128
                                                    3 bed rooms+hall               132919
                            Studio                  Studio                          27462
                            Labor Camps             Room in labor Camp              17970
                            Flat                    4 bed rooms+hall                 8225
                                                    5 bed rooms+hall                  676
                                                    Duplex                            498
                            Labor Camps             Studio                            407
                    

I’ll filter the `ejari_property_type_en` column to include the following residential categories: **“Flat”**, **“Villa”**, **“Studio”**, **“Complex Villas”**, **“Arabian House”**, and **“Penthouse”**. This selection aligns with our focus on core residential property types and will streamline further analysis.

Since there are only about **168** missing (**NaN**) values in `ejari_property_type_en`, it’s reasonable to leave them out to maintain data integrity, given their small proportion relative to the dataset size. This approach will help keep the dataset clean and focused on clearly defined property categories.

In [55]:
# Define the property types we want to keep
selected_property_types = ["Flat", "Villa", "Studio", "Complex Villas", "Arabian House", "Penthouse"]

# Filter the DataFrame to keep only the rows with the specified property types and exclude NaN values
filtered_rent_contracts = rent_contracts_unit_villa[
    rent_contracts_unit_villa['ejari_property_type_en'].isin(selected_property_types)
]

# Comparing shapes before and after filtering
print("Rent Contracts Before Filtering:", rent_contracts_unit_villa.shape)
print("Rent Contracts After Filtering:", filtered_rent_contracts.shape)


Rent Contracts Before Filtering: (2037423, 25)
Rent Contracts After Filtering: (1989336, 25)


In [56]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
filtered_rent_contracts.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709938
                                                    2 bed rooms+hall               609748
                                                    Studio                         302128
                                                    3 bed rooms+hall               132919
                                                    4 bed rooms+hall                 8225
                                                    5 bed rooms+hall                  676
                                                    Duplex                            498
                                                    NaN                               323
                                                    Penthouse                         288
                                                    Office                            226
                    

Looking at the filtered table, here are a few observations and inconsistencies worth noting:

1. **Mixed Property Types in Hierarchies**:

	- Under the `ejari_bus_property_type_en` of **“Unit”**, there are entries classified as **“Villa”**, which should logically only appear under **“Villa”** in the broader hierarchy. This suggests some misclassification.

	- Similarly, in the **“Villa”** category within `ejari_bus_property_type_en`, we see **“Flat”** and **“Studio”** as `ejari_property_type_en` values. These should typically belong to **“Unit”**, as they usually represent apartment-like structures rather than standalone properties like villas.

2. Anomalies in `ejari_property_sub_type_en`:

	- There are entries like **“Office”** and **“Room in labor Camp”** under **“Unit”**, which do not align with the residential focus. Non-residential subtypes should be filtered out if our objective is residential analysis.

	- Unusual subtypes, such as **“Boardroom”** and **“Pharmacy”**, also appear, which likely stem from inconsistent data entry or incorrect mappings.

3. **NaN Values**:

	- There are a small number of **NaN** values under `ejari_property_type_en` and `ejari_property_sub_type_en`. It may be worth investigating these to determine if they can be clarified based on other available columns or simply removed if they represent noise in the dataset.

4. **High Variability in Subtypes**:

	- Subtypes like **“1bed room+Hall”** or **“2 bed rooms+hall”** appear under both **“Flat”** and **“Villa”** categories. This inconsistency could be due to data entry errors or a lack of clear categorization in the original dataset. Such cases might benefit from further consolidation or standardized grouping.

First, let’s filter out non-residential types by removing entries with subtypes that suggest commercial uses, such as **“Office”**, **“Boardroom”** or **“Pharmacy”**.

In [57]:
# Shape of the dataset before filtering
print("Rent Contracts Shape Before Filtering:", filtered_rent_contracts.shape)

# Filtering out non-residential sub property types
non_residential_sub_types = ['Office', 'Room in labor Camp', 'Hotel', 'Pharmacy', 'Boardroom', 'Shop', 'Commercial villa']

# Filter the DataFrame to keep only the rows with the specified property types
filtered_rent_contracts = filtered_rent_contracts[
    ~filtered_rent_contracts['ejari_property_sub_type_en'].isin(non_residential_sub_types)
]

# Shape of the dataset after filtering
print("Rent Contracts Shape After Filtering:", filtered_rent_contracts.shape)

Rent Contracts Shape Before Filtering: (1989336, 25)
Rent Contracts Shape After Filtering: (1988962, 25)


In [58]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
filtered_rent_contracts.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709938
                                                    2 bed rooms+hall               609748
                                                    Studio                         302128
                                                    3 bed rooms+hall               132919
                                                    4 bed rooms+hall                 8225
                                                    5 bed rooms+hall                  676
                                                    Duplex                            498
                                                    NaN                               323
                                                    Penthouse                         288
                            Villa                   3 bed rooms+hall                  170
                    

In [59]:
# Inspecting the shape of the dataset where "ejari_bus_property_type_en" is "Unit" & "ejari_property_type_en" is "Villa"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa')
].shape 

(574, 25)

In [60]:
# Changing values in the "ejari_property_type" columns where "ejari_bus_property_type" is "Unit" & "ejari_property_type" is "Villa" to "Flat"
# Update both ejari_property_type_en to 'Flat' and ejari_property_type_id to 842 where necessary
filtered_rent_contracts.loc[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa'), 
    ['ejari_property_type_en', 'ejari_property_type_id']
] = ['Flat', 842]

# Confirming the shape of the dataset where "ejari_bus_property_type_en" is "Unit" & "ejari_property_type_en" is "Villa"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa')
].shape 

(0, 25)

In [61]:
# Inspecting the shape of the dataset where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Flat"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat')
].shape 

(100, 25)

In [62]:
# Update both ejari_property_type_en to 'Villa' and ejari_property_type_id to 841 where necessary
filtered_rent_contracts.loc[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat'), 
    ['ejari_property_type_en', 'ejari_property_type_id']
] = ['Villa', 841]

# Confirming the shape of the dataset where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Flat"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat')
].shape 

(0, 25)

In [63]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
filtered_rent_contracts.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709948
                                                    2 bed rooms+hall               609857
                                                    Studio                         302128
                                                    3 bed rooms+hall               133089
                                                    4 bed rooms+hall                 8367
                                                    5 bed rooms+hall                  747
                                                    Duplex                            498
                                                    NaN                               323
                                                    Penthouse                         288
                            Penthouse               Penthouse                          90
                    

In [64]:
# Inspecting where the "ejari_property_type_en" is "Villa" and "ejari_property_sub_type_en" is Studio
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Studio')
].shape

(9, 25)

In [65]:
# Displaying random observations where the "ejari_property_type_en" is "Villa" and "ejari_property_sub_type_en" is Studio
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Studio')
].sample(5)

contract_id  contract_reg_type_id contract_reg_type_en  \
3026847  CNT1441084416                     2                Renew   
4640558  CNT2080496748                     2                Renew   
354802   CRT1531944946                     1                  New   
355538   CRT1533116966                     1                  New   
4240979  CNT2024848402                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
3026847          2021-05-01        2022-04-30            16800          16800   
4640558          2021-01-01        2021-12-31            15000          15000   
354802           2021-08-01        2022-07-31            24000          24000   
355538           2021-08-01        2022-07-31            24000          24000   
4240979          2022-11-01        2025-11-30           675000         225000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
3026847           0.0                         4.0                      Villa   
4640558           0.0                         4.0                      Villa   
354802            0.0                         4.0                      Villa   
355538            0.0                         4.0                      Villa   
4240979           0.0                         4.0                      Villa   

         ejari_property_type_id ejari_property_type_en  \
3026847                   841.0                  Villa   
4640558                   841.0                  Villa   
354802                    841.0                  Villa   
355538                    841.0                  Villa   
4240979                   841.0                  Villa   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
3026847                        11.0                     Studio   
4640558                        11.0                     Studio   
354802                         11.0                     Studio   
355538                         11.0                     Studio   
4240979                        11.0                     Studio   

         project_number project_name_en master_project_en  area_id  \
3026847             NaN             NaN               NaN    232.0   
4640558             NaN             NaN               NaN    375.0   
354802              NaN             NaN               NaN    267.0   
355538              NaN             NaN               NaN    267.0   
4240979             NaN             NaN               NaN    233.0   

            area_name_en  actual_area          nearest_landmark_en  \
3026847           Mirdif         56.0  Dubai International Airport   
4640558  Jumeirah Second         33.0                 Burj Khalifa   
354802          Al Raffa          NaN                 Burj Khalifa   
355538          Al Raffa          NaN                 Burj Khalifa   
4240979       Hor Al Anz        343.0  Dubai International Airport   

                            nearest_metro_en     nearest_mall_en  \
3026847              Rashidiya Metro Station  City Centre Mirdif   
4640558           Business Bay Metro Station          Dubai Mall   
354802               Al Fahidi Metro Station          Dubai Mall   
355538               Al Fahidi Metro Station          Dubai Mall   
4240979  Abu Baker Al Siddique Metro Station  City Centre Mirdif   

         tenant_type_id tenant_type_en  
3026847             1.0         Person  
4640558             2.0      Authority  
354802              1.0         Person  
355538              NaN            NaN  
4240979             1.0         Person

In [66]:
# Update records where ejari_property_type_en is 'Villa' and ejari_property_sub_type_en is 'Studio'
filtered_rent_contracts.loc[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Studio'),
    ['ejari_bus_property_type_id', 'ejari_bus_property_type_en', 'ejari_property_type_id', 'ejari_property_type_en']
] = [2.0, 'Unit', 842, 'Flat']

# Confirming update where the "ejari_property_type_en" is "Villa" and "ejari_property_sub_type_en" is Studio
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Studio')
].shape

(0, 25)

In [67]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
filtered_rent_contracts.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709948
                                                    2 bed rooms+hall               609857
                                                    Studio                         302137
                                                    3 bed rooms+hall               133089
                                                    4 bed rooms+hall                 8367
                                                    5 bed rooms+hall                  747
                                                    Duplex                            498
                                                    NaN                               323
                                                    Penthouse                         288
                            Penthouse               Penthouse                          90
                    

In [68]:
# Inspecting values where "ejari_property_type_en" is "Villa" & ejari_property_sub_type_en is "Duplex"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Duplex')
].shape 

(27, 25)

In [69]:
# Displaying random observations where "ejari_property_type_en" is "Villa" & ejari_property_sub_type_en is "Duplex"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Duplex')
].sample(5)

contract_id  contract_reg_type_id contract_reg_type_en  \
3599520  CNT1826013315                     2                Renew   
722839   CRT2078946126                     2                Renew   
755542   CRT2084144966                     2                Renew   
3484815  CNT1784056772                     2                Renew   
4333616  CNT2046643835                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
3599520          2022-01-01        2022-12-31           145000         145000   
722839           2023-02-01        2025-01-31           900000         450000   
755542           2023-01-01        2024-12-31           150000          75000   
3484815          2022-01-01        2022-12-31           240000         240000   
4333616          2023-01-01        2023-12-31           220000         220000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
3599520           0.0                         4.0                      Villa   
722839            0.0                         4.0                      Villa   
755542            0.0                         4.0                      Villa   
3484815           0.0                         4.0                      Villa   
4333616           0.0                         4.0                      Villa   

         ejari_property_type_id ejari_property_type_en  \
3599520                   841.0                  Villa   
722839                    841.0                  Villa   
755542                    841.0                  Villa   
3484815                   841.0                  Villa   
4333616                   841.0                  Villa   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
3599520                        35.0                     Duplex   
722839                         35.0                     Duplex   
755542                         35.0                     Duplex   
3484815                        35.0                     Duplex   
4333616                        35.0                     Duplex   

         project_number project_name_en master_project_en  area_id  \
3599520             NaN             NaN               NaN    278.0   
722839              NaN             NaN               NaN    304.0   
755542              NaN             NaN               NaN    358.0   
3484815             NaN             NaN               NaN    318.0   
4333616             NaN             NaN               NaN    318.0   

             area_name_en  actual_area          nearest_landmark_en  \
3599520          Mankhool          0.0                 Burj Khalifa   
722839   Um Suqaim Second          1.0                 Burj Al Arab   
755542      Al Twar First          NaN  Dubai International Airport   
3484815    Jumeirah Third        533.0                 Burj Khalifa   
4333616    Jumeirah Third        533.0                 Burj Khalifa   

                   nearest_metro_en       nearest_mall_en  tenant_type_id  \
3599520          ADCB Metro Station            Dubai Mall             1.0   
722839      Noor Bank Metro Station  Mall of the Emirates             2.0   
755542       Al Nahda Metro Station    City Centre Mirdif             NaN   
3484815  Business Bay Metro Station            Dubai Mall             1.0   
4333616  Business Bay Metro Station            Dubai Mall             1.0   

        tenant_type_en  
3599520         Person  
722839       Authority  
755542             NaN  
3484815         Person  
4333616         Person

In [70]:
# Update properties classified as 'Villa' with 'Duplex' in the sub-type to 'Unit' and 'Flat' with appropriate IDs
filtered_rent_contracts.loc[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Duplex'),
    ['ejari_bus_property_type_en', 'ejari_bus_property_type_id', 'ejari_property_type_en', 'ejari_property_type_id']
] = ['Unit', 2.0, 'Flat', 842.0]

In [71]:
# Confirming change where "ejari_property_type_en" is "Villa" & ejari_property_sub_type_en is "Duplex"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Duplex')
].shape 

(0, 25)

In [72]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
filtered_rent_contracts.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709948
                                                    2 bed rooms+hall               609857
                                                    Studio                         302137
                                                    3 bed rooms+hall               133089
                                                    4 bed rooms+hall                 8367
                                                    5 bed rooms+hall                  747
                                                    Duplex                            525
                                                    NaN                               323
                                                    Penthouse                         288
                            Penthouse               Penthouse                          90
                    

In [73]:
# Inspecting values where "ejari_bus_property_type_en" is "Unit" & "ejari_property_type_en" is "Arabian House"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Arabian House')
].shape 

(159, 25)

In [74]:
# Update 'Unit' entries labeled as 'Arabian House' to 'Villa' with appropriate IDs
filtered_rent_contracts.loc[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Arabian House'),
    ['ejari_bus_property_type_en', 'ejari_bus_property_type_id']
] = ['Villa', 4.0]

# Confirming change where "ejari_bus_property_type_en" is "Unit" & "ejari_property_type_en" is "Arabian House"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Arabian House')
].shape 

(0, 25)

In [75]:
# Inspecting values where "ejari_bus_property_type_en" is "Unit" & "ejari_property_type_en" is "Complex Villas"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Complex Villas')
].shape 

(16, 25)

In [76]:
# Update 'Unit' entries labeled as 'Complex Villas' to 'Villa' with appropriate IDs
filtered_rent_contracts.loc[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Complex Villas'),
    ['ejari_bus_property_type_en', 'ejari_bus_property_type_id']
] = ['Villa', 4.0]

# Confirming change where "ejari_bus_property_type_en" is "Unit" & "ejari_property_type_en" is "Complex Villas"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Complex Villas')
].shape 

(0, 25)

In [77]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
filtered_rent_contracts.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709948
                                                    2 bed rooms+hall               609857
                                                    Studio                         302137
                                                    3 bed rooms+hall               133089
                                                    4 bed rooms+hall                 8367
                                                    5 bed rooms+hall                  747
                                                    Duplex                            525
                                                    NaN                               323
                                                    Penthouse                         288
                            Penthouse               Penthouse                          90
                    

In [78]:
# Inspecting values where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Complex Villas" 
# & "ejari_property_sub_type_en" is "Duplex"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Complex Villas') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Duplex')
].shape 

(25, 25)

In [79]:
# Displaying random observations where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Complex Villas" 
# & "ejari_property_sub_type_en" is "Duplex"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Complex Villas') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Duplex')
].sample(5)

contract_id  contract_reg_type_id contract_reg_type_en  \
5778261  CNT2118724304                     2                Renew   
3952531  CNT1943246902                     2                Renew   
3951031  CNT1942809185                     2                Renew   
4467475  CNT2066569482                     2                Renew   
4939528  CNT2093034717                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
5778261          2024-08-11        2025-08-10            25000          25000   
3952531          2022-08-10        2023-08-09           145000         145000   
3951031          2022-07-01        2023-06-30            20000          20000   
4467475          2023-02-25        2024-02-24           150000         150000   
4939528          2023-01-10        2024-01-09           100000         100000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
5778261           0.0                         4.0                      Villa   
3952531           0.0                         4.0                      Villa   
3951031           0.0                         4.0                      Villa   
4467475           0.0                         4.0                      Villa   
4939528           0.0                         4.0                      Villa   

         ejari_property_type_id ejari_property_type_en  \
5778261                    19.0         Complex Villas   
3952531                    19.0         Complex Villas   
3951031                    19.0         Complex Villas   
4467475                    19.0         Complex Villas   
4939528                    19.0         Complex Villas   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
5778261                        35.0                     Duplex   
3952531                        35.0                     Duplex   
3951031                        35.0                     Duplex   
4467475                        35.0                     Duplex   
4939528                        35.0                     Duplex   

         project_number project_name_en master_project_en  area_id  \
5778261             NaN             NaN               NaN    399.0   
3952531             NaN             NaN               NaN    315.0   
3951031             NaN             NaN               NaN    399.0   
4467475             NaN             NaN               NaN    315.0   
4939528             NaN             NaN               NaN    315.0   

            area_name_en  actual_area nearest_landmark_en  \
5778261  Al Aweer Second          1.0                 NaN   
3952531        Al Manara        367.0        Burj Al Arab   
3951031  Al Aweer Second          1.0                 NaN   
4467475        Al Manara        367.0        Burj Al Arab   
4939528        Al Manara        367.0        Burj Al Arab   

                           nearest_metro_en       nearest_mall_en  \
5778261                                 NaN                   NaN   
3952531  First Abu Dhabi Bank Metro Station  Mall of the Emirates   
3951031                                 NaN                   NaN   
4467475  First Abu Dhabi Bank Metro Station  Mall of the Emirates   
4939528  First Abu Dhabi Bank Metro Station  Mall of the Emirates   

         tenant_type_id tenant_type_en  
5778261             1.0         Person  
3952531             2.0      Authority  
3951031             1.0         Person  
4467475             1.0         Person  
4939528             1.0         Person

In [80]:
# Update values for records where ejari_bus_property_type_en is 'Villa',
# ejari_property_type_en is 'Complex Villas', and ejari_property_sub_type_en is 'Duplex'
filtered_rent_contracts.loc[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Complex Villas') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Duplex'), 
    ['ejari_bus_property_type_id', 'ejari_bus_property_type_en', 'ejari_property_type_id', 'ejari_property_type_en']
] = [2.0, 'Unit', 842, 'Flat']

# Confirming change where "ejari_bus_property_type_en" is "Villa" & "ejari_property_type_en" is "Complex Villas" 
# & "ejari_property_sub_type_en" is "Duplex"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa') & 
    (filtered_rent_contracts['ejari_property_type_en'] == 'Complex Villas') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Duplex')
].shape 

(0, 25)

In [81]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
filtered_rent_contracts.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709948
                                                    2 bed rooms+hall               609857
                                                    Studio                         302137
                                                    3 bed rooms+hall               133089
                                                    4 bed rooms+hall                 8367
                                                    5 bed rooms+hall                  747
                                                    Duplex                            550
                                                    NaN                               323
                                                    Penthouse                         288
                            Penthouse               Penthouse                          90
                    

In [82]:
# Inspecting values where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is "Penthouse"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Penthouse')
].shape 

(288, 25)

In [83]:
# Inspecting values where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is "Penthouse"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Penthouse')
].sample(5)

contract_id  contract_reg_type_id contract_reg_type_en  \
3806638  CNT1894108816                     2                Renew   
5393623  CNT2109526383                     2                Renew   
5962357  CNT2123234596                     1                  New   
4013431  CNT1964048317                     1                  New   
5383757  CNT2109059449                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
3806638          2022-03-01        2023-02-28           115000         115000   
5393623          2024-02-17        2025-02-16           250000         250000   
5962357          2024-09-11        2025-09-10           290000         290000   
4013431          2022-07-01        2023-06-30           230000         230000   
5383757          2024-03-01        2025-02-28           180000         180000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
3806638           1.0                         2.0                       Unit   
5393623           1.0                         2.0                       Unit   
5962357           1.0                         2.0                       Unit   
4013431           1.0                         2.0                       Unit   
5383757           1.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
3806638                   842.0                   Flat   
5393623                   842.0                   Flat   
5962357                   842.0                   Flat   
4013431                   842.0                   Flat   
5383757                   842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
3806638                       621.0                  Penthouse   
5393623                       621.0                  Penthouse   
5962357                       621.0                  Penthouse   
4013431                       621.0                  Penthouse   
5383757                       621.0                  Penthouse   

         project_number project_name_en               master_project_en  \
3806638          1147.0      TWO TOWERS                    TECOM Site C   
5393623             NaN             NaN  Dubai Health Care City Phase 1   
5962357             NaN             NaN                   Palm Jumeirah   
4013431             NaN             NaN                   Palm Jumeirah   
5383757          1147.0      TWO TOWERS                    TECOM Site C   

         area_id      area_name_en  actual_area          nearest_landmark_en  \
3806638    443.0  Al Thanyah First        171.0                 Burj Al Arab   
5393623    326.0  Um Hurair Second        665.0  Dubai International Airport   
5962357    410.0     Palm Jumeirah        188.0                 Burj Al Arab   
4013431    410.0     Palm Jumeirah        185.0                 Burj Al Arab   
5383757    443.0  Al Thanyah First        170.0                 Burj Al Arab   

                      nearest_metro_en       nearest_mall_en  tenant_type_id  \
3806638            Dubai Internet City  Mall of the Emirates             1.0   
5393623  Healthcare City Metro Station            Dubai Mall             1.0   
5962357                  Palm Jumeirah           Marina Mall             1.0   
4013431                  Palm Jumeirah           Marina Mall             1.0   
5383757            Dubai Internet City  Mall of the Emirates             1.0   

        tenant_type_en  
3806638         Person  
5393623         Person  
5962357         Person  
4013431         Person  
5383757         Person

In [84]:
# Update values for records where ejari_property_type_en is 'Flat' and ejari_property_sub_type_en is 'Penthouse'
filtered_rent_contracts.loc[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Penthouse'), 
    ['ejari_property_type_id', 'ejari_property_type_en', 'ejari_property_sub_type_id', 'ejari_property_sub_type_en']
] = [352361946, 'Penthouse', 621, 'Penthouse']

# Confirming changes where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is "Penthouse"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Penthouse')
].shape 

(0, 25)

In [85]:
# Inspecting the "ejari_bus_property_type", "ejari_property_type" and "ejari_sub_property_type_en" columns grouped together
filtered_rent_contracts.groupby("ejari_bus_property_type_en")[['ejari_property_type_en', 'ejari_property_sub_type_en']].value_counts(dropna=False)

ejari_bus_property_type_en  ejari_property_type_en  ejari_property_sub_type_en 
Unit                        Flat                    1bed room+Hall                 709948
                                                    2 bed rooms+hall               609857
                                                    Studio                         302137
                                                    3 bed rooms+hall               133089
                                                    4 bed rooms+hall                 8367
                                                    5 bed rooms+hall                  747
                                                    Duplex                            550
                            Penthouse               Penthouse                         378
                            Flat                    NaN                               323
                                                    Room                               68
                    

In [86]:
# Inspecting values where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is "Room"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Room')
].shape 

(68, 25)

In [87]:
# Displaying random observations where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is "Room"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Room')
].sample(10)

contract_id  contract_reg_type_id contract_reg_type_en  \
4315996  CNT2042972321                     1                  New   
5328104  CNT2107868450                     1                  New   
4514841  CNT2071830563                     1                  New   
5937725  CNT2122793391                     2                Renew   
5270266  CNT2106481365                     2                Renew   
3616235  CNT1831747121                     2                Renew   
3050399  CNT1450687753                     2                Renew   
2809101  CNT1358122195                     1                  New   
4306909  CNT2041150881                     2                Renew   
4076391  CNT1985024732                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
4315996          2022-11-17        2023-11-16            30000          30000   
5328104          2024-02-06        2024-09-30            28070          43001   
4514841          2022-12-01        2023-11-30            28000          28000   
5937725          2024-10-10        2025-10-09            30188          30188   
5270266          2024-01-01        2024-12-31            34000          34000   
3616235          2021-07-04        2022-07-03            26400          26400   
3050399          2021-05-02        2021-11-01            30000          60000   
2809101          2021-01-03        2022-01-14            24000          24000   
4306909          2022-11-17        2023-11-16            30000          30000   
4076391          2022-09-01        2023-08-31            24300          24300   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
4315996           0.0                         2.0                       Unit   
5328104           0.0                         2.0                       Unit   
4514841           0.0                         2.0                       Unit   
5937725           1.0                         2.0                       Unit   
5270266           0.0                         2.0                       Unit   
3616235           0.0                         2.0                       Unit   
3050399           0.0                         2.0                       Unit   
2809101           0.0                         2.0                       Unit   
4306909           0.0                         2.0                       Unit   
4076391           0.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
4315996                   842.0                   Flat   
5328104                   842.0                   Flat   
4514841                   842.0                   Flat   
5937725                   842.0                   Flat   
5270266                   842.0                   Flat   
3616235                   842.0                   Flat   
3050399                   842.0                   Flat   
2809101                   842.0                   Flat   
4306909                   842.0                   Flat   
4076391                   842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
4315996                       601.0                       Room   
5328104                       601.0                       Room   
4514841                       601.0                       Room   
5937725                       601.0                       Room   
5270266                       601.0                       Room   
3616235                       601.0                       Room   
3050399                       601.0                       Room   
2809101                       601.0                       Room   
4306909                       601.0                       Room   
4076391                       601.0                       Room   

         project_number project_name_en             master_project_en  \
4315996             NaN             NaN

In [88]:
# Inspecting the area names where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is "Room"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Room')
]['area_name_en'].value_counts(dropna=False)

area_name_en
Naif                            23
Al Mararr                       14
Al Goze Industrial Second        7
Al Baraha                        6
Port Saeed                       5
Mirdif                           3
Al Rega                          3
Dubai Investment Park Second     3
Al Suq Al Kabeer                 2
Al Muteena                       1
Trade Center First               1
Name: count, dtype: int64

In [89]:
# Inspecting values where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
].shape

(323, 25)

In [90]:
# Displaying random observations where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
].sample(10)

contract_id  contract_reg_type_id contract_reg_type_en  \
3495310  CNT1788709851                     1                  New   
3801215  CNT1892195660                     1                  New   
4932731  CNT2092592118                     2                Renew   
5298725  CNT2107121742                     1                  New   
3894320  CNT1923198310                     2                Renew   
5019831  CNT2097324493                     1                  New   
4714227  CNT2082816099                     1                  New   
5106193  CNT2101432368                     2                Renew   
4320066  CNT2043868036                     1                  New   
4990010  CNT2095988291                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
3495310          2021-12-01        2022-11-30            75000          75000   
3801215          2022-04-15        2023-04-14            50000          50000   
4932731          2023-08-01        2024-07-31            92400          92400   
5298725          2024-02-02        2025-02-01            60000          60000   
3894320          2022-06-19        2023-06-18            30000          30000   
5019831          2023-10-18        2024-10-17            24000          24000   
4714227          2023-05-26        2024-05-25            54000          54000   
5106193          2023-11-04        2024-11-03            30000          30000   
4320066          2022-12-10        2023-12-09            48000          48000   
4990010          2023-10-05        2024-10-04            49000          49000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
3495310           1.0                         2.0                       Unit   
3801215           1.0                         2.0                       Unit   
4932731           1.0                         2.0                       Unit   
5298725           1.0                         2.0                       Unit   
3894320           1.0                         2.0                       Unit   
5019831           1.0                         2.0                       Unit   
4714227           1.0                         2.0                       Unit   
5106193           1.0                         2.0                       Unit   
4320066           1.0                         2.0                       Unit   
4990010           1.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
3495310                   842.0                   Flat   
3801215                   842.0                   Flat   
4932731                   842.0                   Flat   
5298725                   842.0                   Flat   
3894320                   842.0                   Flat   
5019831                   842.0                   Flat   
4714227                   842.0                   Flat   
5106193                   842.0                   Flat   
4320066                   842.0                   Flat   
4990010                   842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
3495310                         0.0                        NaN   
3801215                         0.0                        NaN   
4932731                         0.0                        NaN   
5298725                         0.0                        NaN   
3894320                         0.0                        NaN   
5019831                         0.0                        NaN   
4714227                         0.0                        NaN   
5106193                         0.0                        NaN   
4320066                         0.0                        NaN   
4990010                         0.0                        NaN   

         project_number     project_name_en           master_project_en  \
3495310          1929.0   SIGNATURE L

In [91]:
# Inspecting area names where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
]['area_name_en'].value_counts(dropna=False)

area_name_en
Al Barsha South Fourth               128
Jabal Ali First                       44
Al Hebiah Fifth                       23
Al Hebiah Fourth                      19
Al Thanyah First                      16
Al Hebiah Third                       10
Business Bay                           9
Al Warsan First                        8
Al Jadaf                               8
Palm Jumeirah                          6
Al Khairan First                       5
Burj Khalifa                           5
Hadaeq Sheikh Mohammed Bin Rashid      4
Al Safouh Second                       4
Al Hebiah Second                       4
Al Satwa                               4
Al Thanyah Third                       4
Al Merkadh                             3
Jumeirah First                         3
Al Yelayiss 2                          3
Al Thanyah Fifth                       3
Mirdif                                 2
Jabal Ali Industrial Second            2
Wadi Al Safa 3                         2
Ras

In [92]:
# Inspecting project names where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
]['project_name_en'].value_counts(dropna=False)

project_name_en
SIGNATURE LIVINGS                                                                119
NaN                                                                               49
Westwood By Imtiaz                                                                27
REMRAAM                                                                           23
OASIS TOWER ONE                                                                   10
SANDHURST HOUSE                                                                    8
DAMAC HILLS - GOLF VITA                                                            7
SERENIA RESIDENCES THE PALM                                                        6
HUB CANAL 2 TOWER                                                                  6
GLITZ RESIDENCE 2                                                                  4
CREEK HORIZON                                                                      3
Azizi Star Hotel Apartments                      

In [93]:
# Inspecting actual area statistics where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
]['actual_area'].describe()

count    323.000000
mean      68.600619
std       50.513312
min       34.000000
25%       39.000000
50%       45.000000
75%       78.000000
max      480.000000
Name: actual_area, dtype: float64

In [94]:
# Comparing actual area statistics where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is "Studio"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == 'Studio')
]['actual_area'].describe()

count    3.008240e+05
mean     6.246679e+03
std      1.521118e+06
min      0.000000e+00
25%      3.500000e+01
50%      4.200000e+01
75%      4.600000e+01
max      3.731260e+08
Name: actual_area, dtype: float64

In [95]:
# Comparing actual area statistics where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is "1bed room+Hall"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == '1bed room+Hall')
]['actual_area'].describe()


count    7.024380e+05
mean     7.806390e+02
std      2.883211e+05
min      0.000000e+00
25%      6.300000e+01
50%      7.400000e+01
75%      8.500000e+01
max      1.220494e+08
Name: actual_area, dtype: float64

In [96]:
# Group the data by project name and property sub-type
project_subtype_stats = filtered_rent_contracts.groupby(['project_name_en', 'ejari_property_sub_type_en'])['actual_area'].agg(['min', 'max']).reset_index()

# Function to impute missing property sub-type based on area
def impute_property_subtype(row):
    project_name = row['project_name_en']
    subtype = row['ejari_property_sub_type_en']
    area = row['actual_area']
    
    if pd.isna(subtype):
        matching_stats = project_subtype_stats[(project_subtype_stats['project_name_en'] == project_name) & (project_subtype_stats['ejari_property_sub_type_en'].notna())]
        for _, stats_row in matching_stats.iterrows():
            min_area, max_area = stats_row['min'], stats_row['max']
            if area >= min_area and area <= max_area:
                return stats_row['ejari_property_sub_type_en']
    return subtype

# Apply the imputation function to the dataframe
filtered_rent_contracts['ejari_property_sub_type_en'] = filtered_rent_contracts.apply(impute_property_subtype, axis=1)

In [97]:
# Inspecting project names where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
]['project_name_en'].value_counts(dropna=False)

project_name_en
NaN                49
SANDHURST HOUSE     8
Name: count, dtype: int64

In [98]:
# Inspecting values where "ejari_property_type_en" is "Flat" & "project_name_en" is "SANDHURST HOUSE"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['project_name_en'] == 'SANDHURST HOUSE')
]['ejari_property_sub_type_en'].value_counts(dropna=False)

ejari_property_sub_type_en
2 bed rooms+hall    145
1bed room+Hall       77
NaN                   8
Name: count, dtype: int64

In [99]:
# Inspecting values where "ejari_property_type_en" is "Flat" & "project_name_en" is "SANDHURST HOUSE"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['project_name_en'] == 'SANDHURST HOUSE')
].groupby('ejari_property_sub_type_en')['actual_area'].describe()

count        mean        std    min    25%    50%  \
ejari_property_sub_type_en                                                      
1bed room+Hall               77.0   79.402597   2.461598   77.0   77.0   80.0   
2 bed rooms+hall            145.0  138.965517  20.870438  101.0  130.0  133.0   

                              75%    max  
ejari_property_sub_type_en                
1bed room+Hall               80.0   86.0  
2 bed rooms+hall            154.0  204.0

In [100]:
# Define filter for SANDHURST HOUSE flats with NaN in property sub type
sandhurst_flatsa = (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & \
                 (filtered_rent_contracts['project_name_en'] == 'SANDHURST HOUSE') & \
                 (filtered_rent_contracts['ejari_property_sub_type_en'].isna())

# Apply area-based filling for Studio and 1-bedroom categories
filtered_rent_contracts.loc[sandhurst_flatsa & (filtered_rent_contracts['actual_area'].between(47, 48)), 
                            'ejari_property_sub_type_en'] = 'Studio'

# Confirming changes where "ejari_property_type_en" is "Flat" & "project_name_en" is "SANDHURST HOUSE"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    (filtered_rent_contracts['project_name_en'] == 'SANDHURST HOUSE')
]['ejari_property_sub_type_en'].value_counts(dropna=False)

ejari_property_sub_type_en
2 bed rooms+hall    145
1bed room+Hall       77
Studio                8
Name: count, dtype: int64

In [101]:
# Inspecting project names where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
]['project_name_en'].value_counts(dropna=False)

project_name_en
NaN    49
Name: count, dtype: int64

In [102]:
# Inspecting observations where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
].sample(5) 


contract_id  contract_reg_type_id contract_reg_type_en  \
3989777  CNT1956195722                     1                  New   
4130746  CNT1998443896                     2                Renew   
3630643  CNT1836592744                     2                Renew   
2936037  CNT1405790641                     1                  New   
3391657  CNT1712232383                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
3989777          2022-06-19        2023-06-18           115000         115000   
4130746          2022-08-01        2023-07-31            82500          82500   
3630643          2022-02-01        2023-01-31            70000          70000   
2936037          2021-03-15        2022-03-14            24000          24000   
3391657          2021-10-27        2022-10-26            25000          25000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
3989777           1.0                         2.0                       Unit   
4130746           1.0                         2.0                       Unit   
3630643           1.0                         2.0                       Unit   
2936037           1.0                         2.0                       Unit   
3391657           1.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
3989777                   842.0                   Flat   
4130746                   842.0                   Flat   
3630643                   842.0                   Flat   
2936037                   842.0                   Flat   
3391657                   842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
3989777                         0.0                        NaN   
4130746                         0.0                        NaN   
3630643                         0.0                        NaN   
2936037                         0.0                        NaN   
3391657                         0.0                        NaN   

         project_number project_name_en           master_project_en  area_id  \
3989777             NaN             NaN                TECOM Site A    371.0   
4130746             NaN             NaN                TECOM Site C    443.0   
3630643             NaN             NaN                TECOM Site C    443.0   
2936037             NaN             NaN  International City Phase 1    343.0   
3391657             NaN             NaN                   Al Furjan    445.0   

             area_name_en  actual_area           nearest_landmark_en  \
3989777  Al Safouh Second        107.0                  Burj Al Arab   
4130746  Al Thanyah First        283.0                  Burj Al Arab   
3630643  Al Thanyah First        196.0                  Burj Al Arab   
2936037   Al Warsan First         67.0                           NaN   
3391657   Jabal Ali First         41.0  Sports City Swimming Academy   

                  nearest_metro_en     nearest_mall_en  tenant_type_id  \
3989777              Palm Jumeirah         Marina Mall             1.0   
4130746        Dubai Internet City         Marina Mall             1.0   
3630643        Dubai Internet City         Marina Mall             1.0   
2936037    Rashidiya Metro Station  City Centre Mirdif             1.0   
3391657  Ibn Battuta Metro Station  Ibn-e-Battuta Mall             1.0   

        tenant_type_en  
3989777         Person  
4130746         Person  
3630643         Person  
2936037         Person  
3391657         Person

In [103]:
# Inspecting actual area statistics where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
]['actual_area'].describe()

count     49.000000
mean     134.571429
std       89.202018
min       41.000000
25%       66.000000
50%      107.000000
75%      196.000000
max      480.000000
Name: actual_area, dtype: float64

In [104]:
# Inspecting area names where "ejari_property_type_en" is "Flat" & "ejari_property_sub_type_en" is null
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_type_en'] == 'Flat') & 
    filtered_rent_contracts['ejari_property_sub_type_en'].isna()
]['area_name_en'].value_counts(dropna=False)

area_name_en
Al Thanyah First                16
Jabal Ali First                 11
Al Warsan First                  6
Al Thanyah Third                 4
Al Satwa                         4
Al Safouh Second                 4
Ras Al Khor Industrial Third     2
Wadi Al Safa 3                   2
Name: count, dtype: int64

In [105]:
# Group the data by area name and property sub-type
area_subtype_stats = filtered_rent_contracts.groupby(['area_name_en', 'ejari_property_sub_type_en'])['actual_area'].agg(['min', 'max']).reset_index()

# Function to impute missing property sub-type based on area
def impute_property_subtype(row):
    area_name = row['area_name_en']
    subtype = row['ejari_property_sub_type_en']
    actual_area = row['actual_area']
    
    if pd.isna(subtype):
        matching_stats = area_subtype_stats[
            (area_subtype_stats['area_name_en'] == area_name) & 
            (area_subtype_stats['ejari_property_sub_type_en'].notna()) &
            (area_subtype_stats['ejari_property_sub_type_en'].isin(['Studio', '1bed room+Hall', '2 bed rooms+hall']))
        ]
        for _, stats_row in matching_stats.iterrows():
            min_area, max_area = stats_row['min'], stats_row['max']
            if actual_area >= min_area and actual_area <= max_area:
                return stats_row['ejari_property_sub_type_en']
    return subtype

# Apply the imputation function to the dataframe
filtered_rent_contracts['ejari_property_sub_type_en'] = filtered_rent_contracts.apply(impute_property_subtype, axis=1)

# Check the results
print("Distribution of property subtypes after imputation:")
print(filtered_rent_contracts['ejari_property_sub_type_en'].value_counts(dropna=False))

Distribution of property subtypes after imputation:
ejari_property_sub_type_en
1bed room+Hall                 711917
2 bed rooms+hall               626787
Studio                         302274
3 bed rooms+hall               229167
4 bed rooms+hall                78110
5 bed rooms+hall                30531
6 bed rooms+hall                 5844
7 bed rooms+hall                 1437
8 bed rooms+hall                  986
Duplex                            550
10 bed rooms+hall                 460
Penthouse                         378
9 bed rooms+hall                  360
Room                               68
11 bed rooms+hall                  51
15 bed room+hall                   22
2 bed rooms+hall+Maids Room        20
Name: count, dtype: int64


In [106]:
# Creating a map of the numbers to fix the "ejari_property_sub_type_id" column
sub_type_id_map = filtered_rent_contracts.groupby('ejari_property_sub_type_en')['ejari_property_sub_type_id'].first().to_dict()
sub_type_id_map

{'10 bed rooms+hall': 10.0,
 '11 bed rooms+hall': 875988406.0,
 '15 bed room+hall': 801092396.0,
 '1bed room+Hall': 1.0,
 '2 bed rooms+hall': 2.0,
 '2 bed rooms+hall+Maids Room': 170501486.0,
 '3 bed rooms+hall': 3.0,
 '4 bed rooms+hall': 4.0,
 '5 bed rooms+hall': 5.0,
 '6 bed rooms+hall': 6.0,
 '7 bed rooms+hall': 7.0,
 '8 bed rooms+hall': 8.0,
 '9 bed rooms+hall': 9.0,
 'Duplex': 35.0,
 'Penthouse': 621.0,
 'Room': 601.0,
 'Studio': 11.0}

In [107]:
# Update the "ejari_property_sub_type_id" column based on the mapping
filtered_rent_contracts['ejari_property_sub_type_id'] = filtered_rent_contracts['ejari_property_sub_type_en'].map(sub_type_id_map)

In [108]:
# Displaying random observations where "ejari_property_sub_type_en" is "2 bed rooms+hall+Maids Room"
filtered_rent_contracts[
    filtered_rent_contracts['ejari_property_sub_type_en'] == '2 bed rooms+hall+Maids Room'
].sample(5)

contract_id  contract_reg_type_id contract_reg_type_en  \
5651649  CNT2115424400                     2                Renew   
5747252  CNT2117947455                     2                Renew   
4659032  CNT2081214580                     2                Renew   
3134854  CNT1500896508                     1                  New   
5710589  CNT2117104441                     2                Renew   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
5651649          2024-07-01        2025-06-30            80000          80000   
5747252          2022-02-07        2023-02-06            45000          45000   
4659032          2022-12-01        2023-11-30            70000          70000   
3134854          2021-08-01        2022-07-31            48000          48000   
5710589          2023-12-01        2024-11-30            73500          73500   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
5651649           0.0                         2.0                       Unit   
5747252           1.0                         2.0                       Unit   
4659032           1.0                         2.0                       Unit   
3134854           1.0                         2.0                       Unit   
5710589           1.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
5651649                   842.0                   Flat   
5747252                   842.0                   Flat   
4659032                   842.0                   Flat   
3134854                   842.0                   Flat   
5710589                   842.0                   Flat   

         ejari_property_sub_type_id   ejari_property_sub_type_en  \
5651649                 170501486.0  2 bed rooms+hall+Maids Room   
5747252                 170501486.0  2 bed rooms+hall+Maids Room   
4659032                 170501486.0  2 bed rooms+hall+Maids Room   
3134854                 170501486.0  2 bed rooms+hall+Maids Room   
5710589                 170501486.0  2 bed rooms+hall+Maids Room   

         project_number            project_name_en        master_project_en  \
5651649             NaN                        NaN                      NaN   
5747252          1306.0  SEASONS COMMUNITY- SUMMER  Jumeirah Village Circle   
4659032             NaN                        NaN  Jumeirah Village Circle   
3134854             NaN                        NaN    Jumeirah Lakes Towers   
5710589             NaN                        NaN  Jumeirah Village Circle   

         area_id            area_name_en  actual_area  \
5651649    329.0     Trade Center Second          NaN   
5747252    441.0  Al Barsha South Fourth        118.0   
4659032    441.0  Al Barsha South Fourth        141.0   
3134854    350.0        Al Thanyah Fifth        102.0   
5710589    441.0  Al Barsha South Fourth        141.0   

                  nearest_landmark_en                      nearest_metro_en  \
5651649                  Burj Khalifa  Buj Khalifa Dubai Mall Metro Station   
5747252  Sports City Swimming Academy                 Nakheel Metro Station   
4659032  Sports City Swimming Academy                   Dubai Internet City   
3134854  Sports City Swimming Academy                 Jumeirah Lakes Towers   
5710589  Sports City Swimming Academy                   Dubai Internet City   

              nearest_mall_en  tenant_type_id tenant_type_en  
5651649            Dubai Mall             1.0         Person  
5747252           Marina Mall             1.0         Person  
4659032  Mall of the Emirates             1.0         Person  
3134854           Marina Mall             1.0         Person  
5710589  Mall of the Emirates             1.0         Person

In [109]:
# Replace "2 bed rooms+hall+Maids Room" with "2 bed rooms+hall"
filtered_rent_contracts['ejari_property_sub_type_en'] = filtered_rent_contracts['ejari_property_sub_type_en'].replace(
    '2 bed rooms+hall+Maids Room', '2 bed rooms+hall'
)

# Creating a map of the numbers to fix the "ejari_property_sub_type_id" column
sub_type_id_map = filtered_rent_contracts.groupby('ejari_property_sub_type_en')['ejari_property_sub_type_id'].first().to_dict()

# Update the "ejari_property_sub_type_id" column based on the mapping
filtered_rent_contracts['ejari_property_sub_type_id'] = filtered_rent_contracts['ejari_property_sub_type_en'].map(sub_type_id_map)

# Verify the changes
print("Updated distribution of property subtypes:")
print(filtered_rent_contracts['ejari_property_sub_type_en'].value_counts(dropna=False))

Updated distribution of property subtypes:
ejari_property_sub_type_en
1bed room+Hall       711917
2 bed rooms+hall     626807
Studio               302274
3 bed rooms+hall     229167
4 bed rooms+hall      78110
5 bed rooms+hall      30531
6 bed rooms+hall       5844
7 bed rooms+hall       1437
8 bed rooms+hall        986
Duplex                  550
10 bed rooms+hall       460
Penthouse               378
9 bed rooms+hall        360
Room                     68
11 bed rooms+hall        51
15 bed room+hall         22
Name: count, dtype: int64


In [110]:
# Displaying random observations where "ejari_property_sub_type_en" is "15 bed room+hall"
filtered_rent_contracts[
    filtered_rent_contracts['ejari_property_sub_type_en'] == '15 bed room+hall'
].sample(5)

contract_id  contract_reg_type_id contract_reg_type_en  \
927757  CRT2114863246                     2                Renew   
323313  CRT1481898426                     1                  New   
843634  CRT2103700366                     1                  New   
267589  CRT1382332626                     1                  New   
592682  CRT1970683966                     1                  New   

       contract_start_date contract_end_date  contract_amount  annual_amount  \
927757          2024-05-26        2025-05-25           200000         200000   
323313          2021-01-01        2021-12-31            24000          24000   
843634          2023-11-15        2024-11-14           350000         350000   
267589          2021-02-03        2022-02-02           240000         240000   
592682          2021-09-01        2022-10-31           100000         100000   

        is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
927757           0.0                         4.0                      Villa   
323313           0.0                         4.0                      Villa   
843634           0.0                         4.0                      Villa   
267589           0.0                         4.0                      Villa   
592682           0.0                         4.0                      Villa   

        ejari_property_type_id ejari_property_type_en  \
927757                   841.0                  Villa   
323313                   841.0                  Villa   
843634                   841.0                  Villa   
267589                   841.0                  Villa   
592682                   841.0                  Villa   

        ejari_property_sub_type_id ejari_property_sub_type_en  project_number  \
927757                 801092396.0           15 bed room+hall             NaN   
323313                 801092396.0           15 bed room+hall             NaN   
843634                 801092396.0           15 bed room+hall             NaN   
267589                 801092396.0           15 bed room+hall             NaN   
592682                 801092396.0           15 bed room+hall             NaN   

       project_name_en master_project_en  area_id    area_name_en  \
927757             NaN               NaN    278.0        Mankhool   
323313             NaN               NaN    328.0      Al Jafliya   
843634             NaN               NaN    398.0  Al Aweer First   
267589             NaN               NaN    276.0         Al Bada   
592682             NaN               NaN    382.0       Al Waheda   

        actual_area          nearest_landmark_en           nearest_metro_en  \
927757        959.0                 Burj Khalifa         ADCB Metro Station   
323313          NaN                 Burj Khalifa  Al Jafiliya Metro Station   
843634        445.0                          NaN                        NaN   
267589          NaN                 Burj Khalifa           Financial Centre   
592682          NaN  Dubai International Airport     Abu Hail Metro Station   

       nearest_mall_en  tenant_type_id tenant_type_en  
927757      Dubai Mall             NaN            NaN  
323313      Dubai Mall             1.0         Person  
843634             NaN             1.0         Person  
267589      Dubai Mall             1.0         Person  
592682             NaN             1.0         Person

In [111]:
# Inspecting actual area statistics where "ejari_property_sub_type_en" is "15 bed room+hall"
filtered_rent_contracts[
    filtered_rent_contracts['ejari_property_sub_type_en'] == '15 bed room+hall'
]['actual_area'].describe()

count      17.000000
mean      658.588235
std       516.056690
min         0.000000
25%       151.000000
50%       929.000000
75%       959.000000
max      1747.000000
Name: actual_area, dtype: float64

In [112]:
# Inspecting property type distribution where "ejari_property_sub_type_en" is "15 bed room+hall"
filtered_rent_contracts[
    filtered_rent_contracts['ejari_property_sub_type_en'] == '15 bed room+hall'
]['ejari_property_type_en'].value_counts(dropna=False)

ejari_property_type_en
Villa    18
Flat      4
Name: count, dtype: int64

In [113]:
# Inspecting annual amount statistics where "ejari_property_sub_type_en" is "15 bed room+hall"
filtered_rent_contracts[
    filtered_rent_contracts['ejari_property_sub_type_en'] == '15 bed room+hall'
]['annual_amount'].describe()

count        22.000000
mean     260186.318182
std      141168.775263
min       24000.000000
25%      185000.000000
50%      250000.000000
75%      322500.000000
max      700000.000000
Name: annual_amount, dtype: float64

Looking at these statistics for the "15 bed rooms+hall" category, there are several red flags:

1. **Area Statistics are concerning**:


    - The minimum area is 0 square meters, which is impossible

    - There's a huge variance (std of 516 m²)

    - The range from min (0 m²) to max (1,747 m²) is extremely wide

    - Some of these areas (especially the lower ones) are too small for a 15-bedroom property


2. **Property Type Distribution**:


    - 4 Flats listed as 15 bedrooms is highly unlikely

    - While 18 villas is more plausible for 15 bedrooms, it's still unusually large


3. **Annual Amount Statistics**:


    - The minimum rent of 24,000 is extremely low for a 15-bedroom property

    - Even the median (250,000) seems low for properties of this size

    - The large standard deviation suggests inconsistent data

In [114]:
# Inspecting observations where actual area is 0 & "ejari_property_sub_type_en" is "15 bed room+hall"
filtered_rent_contracts[
    (filtered_rent_contracts['actual_area'] == 0) & 
    (filtered_rent_contracts['ejari_property_sub_type_en'] == '15 bed room+hall')
]

contract_id  contract_reg_type_id contract_reg_type_en  \
357131  CRT1535724236                     1                  New   

       contract_start_date contract_end_date  contract_amount  annual_amount  \
357131          2021-07-01        2022-08-31           210000         210000   

        is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
357131           0.0                         4.0                      Villa   

        ejari_property_type_id ejari_property_type_en  \
357131                   841.0                  Villa   

        ejari_property_sub_type_id ejari_property_sub_type_en  project_number  \
357131                 801092396.0           15 bed room+hall             NaN   

       project_name_en master_project_en  area_id area_name_en  actual_area  \
357131             NaN               NaN    233.0   Hor Al Anz          0.0   

                nearest_landmark_en        nearest_metro_en nearest_mall_en  \
357131  Dubai International Airport  Abu Hail Metro Station             NaN   

        tenant_type_id tenant_type_en  
357131             NaN            NaN

In [115]:
# Create a boolean mask to identify the rows to delete
mask = (filtered_rent_contracts['actual_area'] == 0) & \
       (filtered_rent_contracts['ejari_property_sub_type_en'] == '15 bed room+hall')

# Use the mask to filter out the rows and create a new DataFrame
filtered_rent_contracts = filtered_rent_contracts[~mask] 

# Inspecting actual area statistics where "ejari_property_sub_type_en" is "15 bed room+hall"
filtered_rent_contracts[
    filtered_rent_contracts['ejari_property_sub_type_en'] == '15 bed room+hall'
]['actual_area'].describe()

count      16.000000
mean      699.750000
std       503.334547
min         1.000000
25%       264.250000
50%       929.000000
75%       959.000000
max      1747.000000
Name: actual_area, dtype: float64

In [116]:
# Inspecting area distribution across different "ejari_bus_property_type_en"
filtered_rent_contracts.groupby('ejari_bus_property_type_en')['actual_area'].describe()

count          mean           std  min    25%  \
ejari_bus_property_type_en                                                      
Unit                        1748125.0   3470.633236  1.024440e+06  0.0   57.0   
Villa                        212025.0  12496.505879  2.856844e+06  0.0  175.0   

                              50%    75%          max  
ejari_bus_property_type_en                             
Unit                         83.0  116.0  373126042.0  
Villa                       271.0  457.0  930091045.0

In [117]:
# Shape of the dataset before filtering
print("Rent Contracts Shape Before Filtering:", filtered_rent_contracts.shape)

# Define area limits for each property type
villa_limits = (57, 15200)
unit_limits = (9, 3201)

# Filter observations based on ejari_bus_property_type_en and area limits
filtered_rent_contracts = filtered_rent_contracts[
    ((filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa') & 
     (filtered_rent_contracts['actual_area'].between(*villa_limits))) |
    ((filtered_rent_contracts['ejari_bus_property_type_en'] == 'Unit') & 
     (filtered_rent_contracts['actual_area'].between(*unit_limits)))
].copy()

# Shape of the dataset after filtering
print("Rent Contracts Shape After Filtering:", filtered_rent_contracts.shape)

Rent Contracts Shape Before Filtering: (1988961, 25)
Rent Contracts Shape After Filtering: (1866620, 25)


In [118]:
# Inspecting "ejari_property_sub_type_en" value counts after filtering
print(filtered_rent_contracts['ejari_property_sub_type_en'].value_counts(dropna=False))

ejari_property_sub_type_en
1bed room+Hall       675520
2 bed rooms+hall     588098
Studio               293386
3 bed rooms+hall     210943
4 bed rooms+hall      66933
5 bed rooms+hall      24431
6 bed rooms+hall       4348
7 bed rooms+hall        890
8 bed rooms+hall        569
Duplex                  527
Penthouse               374
10 bed rooms+hall       281
9 bed rooms+hall        202
Room                     65
11 bed rooms+hall        38
15 bed room+hall         15
Name: count, dtype: int64


In [119]:
# Inspecting actual area statistics where "ejari_property_sub_type_en" is "15 bed room+hall"
filtered_rent_contracts[
    (filtered_rent_contracts['ejari_property_sub_type_en'] == '15 bed room+hall') &
    (filtered_rent_contracts['ejari_bus_property_type_en'] == 'Villa')
]['actual_area'].describe()

count      11.000000
mean      970.181818
std       341.225678
min       445.000000
25%       929.000000
50%       959.000000
75%       959.000000
max      1747.000000
Name: actual_area, dtype: float64

To enhance the forecasting accuracy of our model, we are refining the property categories by removing rare, potentially outlier configurations that may not contribute meaningfully to investor insights. Specifically, we plan to:

1. **Remove Irregular Categories**:

	- Exclude properties with 11-bedroom and 15-bedroom configurations. These categories are sparse and introduce substantial variability in actual area sizes, making them unhelpful for reliable predictive modeling.

	- Additionally, the “Room” category will be removed due to its low count and distinct nature from full units.

2. **Consolidate Large Bedroom Counts**:

	- Group properties with 8 to 10 bedrooms into a single category. This approach will capture meaningful insights from larger properties while mitigating inconsistencies due to the variability in area data.

3. **Refine Naming for Clarity**:

	- Standardize the naming convention for other categories (e.g., “1 Bed + Hall” instead of “1bed room+Hall”) to ensure consistency and improve readability in reports and visualizations.

In [120]:
# Standardize the 'ejari_property_sub_type_en' column by stripping whitespace and converting to lowercase
filtered_rent_contracts['ejari_property_sub_type_en'] = filtered_rent_contracts['ejari_property_sub_type_en'].str.strip().str.lower()

# Remove properties with 11-bedroom and 15-bedroom configurations
filtered_rent_contracts = filtered_rent_contracts[
    ~filtered_rent_contracts['ejari_property_sub_type_en'].isin(['11 bed rooms+hall', '15 bed room+hall', 'room'])
]

# Consolidate 8, 9, and 10-bedroom properties into a single category '8-10 Bed + Hall'
filtered_rent_contracts['ejari_property_sub_type_en'] = np.where(
    filtered_rent_contracts['ejari_property_sub_type_en'].isin(['8 bed rooms+hall', '9 bed rooms+hall', '10 bed rooms+hall']),
    '8-10 Bed + Hall',
    filtered_rent_contracts['ejari_property_sub_type_en']
)

# Standardize category names for improved clarity
name_replacements = {
    '1bed room+Hall': '1 Bed + Hall',
    '2 bed rooms+hall': '2 Beds + Hall',
    '3 bed rooms+hall': '3 Beds + Hall',
    '4 bed rooms+hall': '4 Beds + Hall',
    '5 bed rooms+hall': '5 Beds + Hall',
    '6 bed rooms+hall': '6 Beds + Hall',
    '7 bed rooms+hall': '7 Beds + Hall',
    'Studio': 'Studio',
    'Duplex': 'Duplex',
    'Penthouse': 'Penthouse'
}

filtered_rent_contracts['ejari_property_sub_type_en'] = filtered_rent_contracts['ejari_property_sub_type_en'].replace(name_replacements)

# Verifying the changes
print(filtered_rent_contracts['ejari_property_sub_type_en'].value_counts())

ejari_property_sub_type_en
1bed room+hall     675520
2 Beds + Hall      588098
studio             293386
3 Beds + Hall      210943
4 Beds + Hall       66933
5 Beds + Hall       24431
6 Beds + Hall        4348
8-10 Bed + Hall      1052
7 Beds + Hall         890
duplex                527
penthouse             374
Name: count, dtype: int64


In [121]:
# Displaying missing values percentages for each column
filtered_rent_contracts.isnull().sum() / filtered_rent_contracts.shape[0] * 100

contract_id                    0.000000
contract_reg_type_id           0.000000
contract_reg_type_en           0.000000
contract_start_date            0.000000
contract_end_date              0.000000
contract_amount                0.000000
annual_amount                  0.000000
is_free_hold                   0.000000
ejari_bus_property_type_id     0.000000
ejari_bus_property_type_en     0.000000
ejari_property_type_id         0.000000
ejari_property_type_en         0.000000
ejari_property_sub_type_id     0.000000
ejari_property_sub_type_en     0.000000
project_number                72.104075
project_name_en               72.104075
master_project_en             49.113475
area_id                        0.000000
area_name_en                   0.000000
actual_area                    0.000000
nearest_landmark_en            8.662514
nearest_metro_en              15.150640
nearest_mall_en               15.754818
tenant_type_id                 8.798651
tenant_type_en                 8.798651


In [122]:
# Displaying random observations of the dataset
display(filtered_rent_contracts.sample(5))

contract_id  contract_reg_type_id contract_reg_type_en  \
774386   CRT2087963242                     1                  New   
4163802  CNT2005765815                     2                Renew   
4865240  CNT2089376567                     2                Renew   
5620481  CNT2114867153                     1                  New   
925220   CRT2114373706                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
774386           2023-07-01        2024-06-30            50000          50000   
4163802          2022-10-22        2023-10-21            38000          38000   
4865240          2023-09-18        2024-09-17            28500          28500   
5620481          2024-06-01        2025-05-31            53000          53000   
925220           2024-06-05        2025-06-04           180000         180000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
774386            1.0                         2.0                       Unit   
4163802           0.0                         2.0                       Unit   
4865240           1.0                         2.0                       Unit   
5620481           0.0                         2.0                       Unit   
925220            1.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
774386                    842.0                   Flat   
4163802                   842.0                   Flat   
4865240                   842.0                   Flat   
5620481                   842.0                   Flat   
925220                    842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
774386                          2.0              2 Beds + Hall   
4163802                         2.0              2 Beds + Hall   
4865240                        11.0                     studio   
5620481                         2.0              2 Beds + Hall   
925220                          3.0              3 Beds + Hall   

         project_number project_name_en                master_project_en  \
774386           1583.0     DUBAI WHARF                  Culture Village   
4163802             NaN             NaN                              NaN   
4865240             NaN             NaN                              NaN   
5620481             NaN             NaN                              NaN   
925220              NaN             NaN  Jumeriah Beach Residence  - JBR   

         area_id                  area_name_en  actual_area  \
774386     334.0                      Al Jadaf        140.0   
4163802    342.0  Ras Al Khor Industrial Third         85.0   
4865240    372.0     Al Goze Industrial Second         38.0   
5620481    367.0              Al Suq Al Kabeer         46.0   
925220     330.0                   Marsa Dubai        178.0   

                 nearest_landmark_en          nearest_metro_en  \
774386   Dubai International Airport    Al Jadaf Metro Station   
4163802  Dubai International Airport   Rashidiya Metro Station   
4865240               Downtown Dubai   Noor Bank Metro Station   
5620481  Dubai International Airport   Al Fahidi Metro Station   
925220                  Burj Al Arab  Jumeirah Beach Residency   

              nearest_mall_en  tenant_type_id tenant_type_en  
774386             Dubai Mall             1.0         Person  
4163802    City Centre Mirdif             1.0         Person  
4865240  Mall of the Emirates             1.0         Person  
5620481            Dubai Mall             1.0         Person  
925220            Marina Mall             1.0         Person

In [123]:
# Displaying the cintract_amount statistics for each tenant type
display(filtered_rent_contracts.groupby("tenant_type_en")['contract_amount'].describe())

count          mean           std  min      25%      50%  \
tenant_type_en                                                                 
Authority        116371.0  64841.493018  2.681081e+05  0.0  32000.0  47000.0   
Person          1585904.0  73473.066720  2.662165e+06  0.0  36000.0  50820.0   

                    75%           max  
tenant_type_en                         
Authority       68000.0  8.000000e+07  
Person          78000.0  3.300038e+09

We're dropping the `tenant_type_id` and `tenant_type_en` columns because they don't seem to provide much useful information for our analysis.  The limited categories and skewed distribution suggest they won't be strong predictors of rental prices or investment potential.

In [124]:
# Dropping tenant type columns from the dataset
filtered_rent_contracts = filtered_rent_contracts.drop(columns=['tenant_type_id', 'tenant_type_en'])

# Confirming changes by displaying the dataset shape
print("Rent Contracts Shape After Dropping Tenant Type Columns:", filtered_rent_contracts.shape)

Rent Contracts Shape After Dropping Tenant Type Columns: (1866502, 23)


Let's start with cleaning and validating `contract_amount` and `annual_amount` to remove zeroes and filter outliers. Ensuring realistic values in these columns is essential for accurate financial analysis and reliable investment insights.

In [125]:
# Changing scientific notation to float
pd.set_option('display.float_format', lambda x: '%.6f' % x)

In [126]:
# Statistical summary of contract_amount & annual_amount columns
print(filtered_rent_contracts[['contract_amount', 'annual_amount']].describe())

        contract_amount     annual_amount
count    1866502.000000    1866502.000000
mean       74774.936507      74511.775176
std      2455389.326710    2449258.616803
min            0.000000          0.000000
25%        36000.000000      37000.000000
50%        51975.000000      52000.000000
75%        80000.000000      80000.000000
max   3300037950.000000 3300037950.000000


These statistics show that both contract_amount and annual_amount columns have outliers and values set to zero, which may distort analysis. Given that min is zero, yet realistic values start at the 25th percentile, we could remove zeroes and examine the extreme high values (likely outliers). The substantial difference between mean and median (50%) suggests skewness, likely due to those high-value outliers.

In [127]:
# Filter out rows with zero values in contract_amount or annual_amount
filtered_rent_contracts = filtered_rent_contracts[
    (filtered_rent_contracts['contract_amount'] > 0) &
    (filtered_rent_contracts['annual_amount'] > 0)
]

# Check new statistics to confirm the removal
print(filtered_rent_contracts[['contract_amount', 'annual_amount']].describe())

        contract_amount     annual_amount
count    1866488.000000    1866488.000000
mean       74775.497372      74512.334068
std      2455398.526749    2449267.793889
min            1.000000          1.000000
25%        36000.000000      37000.000000
50%        51975.000000      52000.000000
75%        80000.000000      80000.000000
max   3300037950.000000 3300037950.000000


In [128]:
# Inspecting the unbeleivable max contract amount
filtered_rent_contracts.loc[
    filtered_rent_contracts['contract_amount'].idxmax()
]

contract_id                                  CRT2079944156
contract_reg_type_id                                     2
contract_reg_type_en                                 Renew
contract_start_date                    2023-04-01 00:00:00
contract_end_date                      2024-03-31 00:00:00
contract_amount                                 3300037950
annual_amount                                   3300037950
is_free_hold                                      1.000000
ejari_bus_property_type_id                        2.000000
ejari_bus_property_type_en                            Unit
ejari_property_type_id                          842.000000
ejari_property_type_en                                Flat
ejari_property_sub_type_id                        1.000000
ejari_property_sub_type_en                  1bed room+hall
project_number                                  331.000000
project_name_en                   ELITE 3 SPORTS RESIDENCE
master_project_en                        Dubai Sports Ci

In [129]:
# Calculate the 1st and 99th percentiles for both contract and annual amounts
lower_contract, upper_contract = filtered_rent_contracts['contract_amount'].quantile([0.01, 0.99])
lower_annual, upper_annual = filtered_rent_contracts['annual_amount'].quantile([0.01, 0.99])

# Filter the dataset to retain only values within the 1st and 99th percentiles for both columns
filtered_rent_contracts = filtered_rent_contracts[
    (filtered_rent_contracts['contract_amount'] >= lower_contract) & 
    (filtered_rent_contracts['contract_amount'] <= upper_contract) &
    (filtered_rent_contracts['annual_amount'] >= lower_annual) &
    (filtered_rent_contracts['annual_amount'] <= upper_annual)
]

# Statistical summary of contract_amount & annual_amount columns
print(filtered_rent_contracts[['contract_amount', 'annual_amount']].describe())

       contract_amount  annual_amount
count   1813711.000000 1813711.000000
mean      66676.892952   67296.590671
std       46605.625814   46502.085698
min       13915.000000   17500.000000
25%       37000.000000   37500.000000
50%       52000.000000   52174.000000
75%       80000.000000   80000.000000
max      336000.000000  320000.000000


In [130]:
# Changing scientific notation back
pd.reset_option('display.float_format')

In [131]:
# Displaying random observations of the dataset
display(filtered_rent_contracts.sample(5))

contract_id  contract_reg_type_id contract_reg_type_en  \
617156   CRT1998147847                     2                Renew   
3947886  CNT1941741875                     2                Renew   
3306440  CNT1635924243                     1                  New   
5725103  CNT2117377300                     2                Renew   
4872703  CNT2089670490                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
617156           2022-05-29        2023-05-28           110000         110000   
3947886          2021-06-15        2022-06-14            18275          18275   
3306440          2021-10-12        2022-10-11            77500          77500   
5725103          2024-06-01        2025-05-31           109148         109148   
4872703          2023-08-15        2024-08-14            55000          55000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
617156            1.0                         2.0                       Unit   
3947886           1.0                         2.0                       Unit   
3306440           1.0                         2.0                       Unit   
5725103           1.0                         2.0                       Unit   
4872703           0.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
617156                    842.0                   Flat   
3947886                   842.0                   Flat   
3306440                   842.0                   Flat   
5725103                   842.0                   Flat   
4872703                   842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
617156                          2.0              2 Beds + Hall   
3947886                        11.0                     studio   
3306440                         2.0              2 Beds + Hall   
5725103                         3.0              3 Beds + Hall   
4872703                         2.0              2 Beds + Hall   

         project_number   project_name_en           master_project_en  \
617156           1297.0  MARINA RESIDENCE               Palm Jumeirah   
3947886             NaN               NaN  International City Phase 1   
3306440             NaN               NaN                TECOM Site A   
5725103             NaN               NaN     Jumeirah Village Circle   
4872703             NaN               NaN                         NaN   

         area_id            area_name_en  actual_area  \
617156     410.0           Palm Jumeirah        190.0   
3947886    343.0         Al Warsan First         44.0   
3306440    371.0        Al Safouh Second        162.0   
5725103    441.0  Al Barsha South Fourth        350.0   
4872703    355.0          Al Nahda First        128.0   

                  nearest_landmark_en         nearest_metro_en  \
617156                   Burj Al Arab            Palm Jumeirah   
3947886                           NaN  Rashidiya Metro Station   
3306440                  Burj Al Arab      Dubai Internet City   
5725103  Sports City Swimming Academy      Dubai Internet City   
4872703   Dubai International Airport    STADIUM Metro Station   

              nearest_mall_en  
617156            Marina Mall  
3947886    City Centre Mirdif  
3306440  Mall of the Emirates  
5725103           Marina Mall  
4872703    City Centre Mirdif

In [132]:
# Displaying missing values percentages in the dataset
filtered_rent_contracts.isnull().sum() / filtered_rent_contracts.shape[0] * 100

contract_id                    0.000000
contract_reg_type_id           0.000000
contract_reg_type_en           0.000000
contract_start_date            0.000000
contract_end_date              0.000000
contract_amount                0.000000
annual_amount                  0.000000
is_free_hold                   0.000000
ejari_bus_property_type_id     0.000000
ejari_bus_property_type_en     0.000000
ejari_property_type_id         0.000000
ejari_property_type_en         0.000000
ejari_property_sub_type_id     0.000000
ejari_property_sub_type_en     0.000000
project_number                72.140545
project_name_en               72.140545
master_project_en             49.138038
area_id                        0.000000
area_name_en                   0.000000
actual_area                    0.000000
nearest_landmark_en            8.562831
nearest_metro_en              15.223043
nearest_mall_en               15.813048
dtype: float64

Upon reviewing the transaction dataset, we found that the data in the nearest amenities column lacked accuracy and did not contribute meaningful insights. To maintain data quality and ensure that only relevant features are included, we will remove the nearest amenities column from this dataset as well.

In [133]:
# Selecting columns to drop
amenities_columns = [col for col in filtered_rent_contracts.columns if 'nearest' in col]

# Drop the 'nearest_amenities' column due to data inaccuracy
filtered_rent_contracts = filtered_rent_contracts.drop(columns=amenities_columns)

# Confirm column removal
print("Rent Contracts Shape After Dropping Amenities Columns:", filtered_rent_contracts.shape)

Rent Contracts Shape After Dropping Amenities Columns: (1813711, 20)


In [134]:
# Creating a dataset that matches the transactions dataset
master_project_rent_contracts = filtered_rent_contracts[
    filtered_rent_contracts['project_number'].notnull()
].copy()

# Comparing shapes before and after filtering
print("Rent Contracts Before Filtering:", filtered_rent_contracts.shape)
print("Rent Contracts After Filtering:", master_project_rent_contracts.shape)

Rent Contracts Before Filtering: (1813711, 20)
Rent Contracts After Filtering: (505290, 20)


In [135]:
# Displaying random observations of the dataset
display(master_project_rent_contracts.sample(5))

contract_id  contract_reg_type_id contract_reg_type_en  \
5351306  CNT2108444217                     2                Renew   
337174   CRT1502298156                     1                  New   
5261507  CNT2106374036                     1                  New   
5158781  CNT2103777572                     1                  New   
904754   CRT2111825296                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
5351306          2024-02-14        2025-02-13            51060          51060   
337174           2021-07-08        2022-07-07            87000          87000   
5261507          2024-01-19        2025-01-18           220000         220000   
5158781          2023-12-04        2024-12-03            54000          54000   
904754           2024-04-01        2025-03-31            35000          35000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
5351306           1.0                         2.0                       Unit   
337174            1.0                         2.0                       Unit   
5261507           1.0                         4.0                      Villa   
5158781           1.0                         2.0                       Unit   
904754            1.0                         2.0                       Unit   

         ejari_property_type_id ejari_property_type_en  \
5351306                   842.0                   Flat   
337174                    842.0                   Flat   
5261507                   841.0                  Villa   
5158781                   842.0                   Flat   
904754                    842.0                   Flat   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
5351306                        11.0                     studio   
337174                          2.0              2 Beds + Hall   
5261507                         4.0              4 Beds + Hall   
5158781                        11.0                     studio   
904754                         11.0                     studio   

         project_number         project_name_en        master_project_en  \
5351306           567.0          BURJ AL NUJOOM             Burj Khalifa   
337174           1776.0              Studio One             Dubai Marina   
5261507          2205.0                    Elan            TILAL AL GHAF   
5158781          1752.0       CRYSTAL RESIDENCE  Jumeirah Village Circle   
904754            806.0  UNIESTATE SPORTS TOWER        Dubai Sports City   

         area_id            area_name_en  actual_area  
5351306    390.0            Burj Khalifa         42.0  
337174     330.0             Marsa Dubai         78.0  
5261507    435.0        Al Hebiah Fourth        198.0  
5158781    441.0  Al Barsha South Fourth         39.0  
904754     435.0        Al Hebiah Fourth         40.0

In [136]:
# Missing data in the master_project_rent_contracts dataset
master_project_rent_contracts.isnull().sum() / master_project_rent_contracts.shape[0] * 100

contract_id                   0.000000
contract_reg_type_id          0.000000
contract_reg_type_en          0.000000
contract_start_date           0.000000
contract_end_date             0.000000
contract_amount               0.000000
annual_amount                 0.000000
is_free_hold                  0.000000
ejari_bus_property_type_id    0.000000
ejari_bus_property_type_en    0.000000
ejari_property_type_id        0.000000
ejari_property_type_en        0.000000
ejari_property_sub_type_id    0.000000
ejari_property_sub_type_en    0.000000
project_number                0.000000
project_name_en               0.000000
master_project_en             9.400146
area_id                       0.000000
area_name_en                  0.000000
actual_area                   0.000000
dtype: float64

In [137]:
# Displaying observations where "master_project_en" is null
display(master_project_rent_contracts[
    master_project_rent_contracts['master_project_en'].isnull()
].sample(5))

contract_id  contract_reg_type_id contract_reg_type_en  \
344692   CRT1513331226                     1                  New   
291086   CRT1417778596                     2                Renew   
5126785  CNT2102319444                     1                  New   
848534   CRT2104297586                     1                  New   
4461213  CNT2065945429                     1                  New   

        contract_start_date contract_end_date  contract_amount  annual_amount  \
344692           2021-07-15        2022-07-14            97000          97000   
291086           2021-03-15        2022-03-14            87000          87000   
5126785          2023-11-22        2024-11-21           182500         182500   
848534           2023-11-20        2024-11-19            88000          88000   
4461213          2023-02-06        2024-02-05           127000         127000   

         is_free_hold  ejari_bus_property_type_id ejari_bus_property_type_en  \
344692            1.0                         4.0                      Villa   
291086            1.0                         4.0                      Villa   
5126785           1.0                         2.0                       Unit   
848534            1.0                         2.0                       Unit   
4461213           1.0                         4.0                      Villa   

         ejari_property_type_id ejari_property_type_en  \
344692                    841.0                  Villa   
291086                    841.0                  Villa   
5126785                   842.0                   Flat   
848534                    842.0                   Flat   
4461213                   841.0                  Villa   

         ejari_property_sub_type_id ejari_property_sub_type_en  \
344692                          3.0              3 Beds + Hall   
291086                          3.0              3 Beds + Hall   
5126785                         2.0              2 Beds + Hall   
848534                          1.0             1bed room+hall   
4461213                         3.0              3 Beds + Hall   

         project_number                      project_name_en  \
344692           1825.0             REEM-MIRA COMMUNITY PH 4   
291086           1500.0  REEM - MIRA OASIS COMMUNITY PHASE 3   
5126785          1665.0   PARAMOUNT TOWER HOTEL & RESIDENCES   
848534           2305.0          Sobha Hartland Waves Grande   
4461213          2057.0                 Villanova Amaranta 3   

        master_project_en  area_id    area_name_en  actual_area  
344692                NaN    506.0   Al Yelayiss 1        216.0  
291086                NaN    506.0   Al Yelayiss 1        328.0  
5126785               NaN    526.0    Business Bay        120.0  
848534                NaN    412.0      Al Merkadh         66.0  
4461213               NaN    467.0  Wadi Al Safa 5        161.0

In [138]:
filtered_rent_contracts['contract_start_date'].dt.year.value_counts()

contract_start_date
2023    503270
2022    468029
2024    427465
2021    414143
2025       804
Name: count, dtype: int64

In [139]:
# Saving both datasets separately
filtered_rent_contracts.to_csv('../data/processed/filtered_rent_contracts.csv', index=False)
master_project_rent_contracts.to_csv('../data/processed/master_project_rent_contracts.csv', index=False)

In [140]:
filtered_rent_contracts.shape 

(1813711, 20)